import { Category } from './types';

export const CATEGORIES: Category[] = [
  {
    number: 1,
    title: 'Neural Network Foundations',
    slug: 'neural-foundations',
    summary: 'Core building blocks of artificial neural networks: perceptrons, activations, backpropagation, and loss functions.',
    conceptCount: 15,
    range: [1, 15],
  },
  {
    number: 2,
    title: 'Text Representation',
    slug: 'text-representation',
    summary: 'Methods for turning words, characters, and sentences into numerical vectors for machine learning.',
    conceptCount: 12,
    range: [16, 27],
  },
  {
    number: 3,
    title: 'Tokenization in Detail',
    slug: 'tokenization',
    summary: 'Algorithms and strategies for splitting text into subwords, characters, and vocabulary tokens.',
    conceptCount: 10,
    range: [28, 37],
  },
  {
    number: 4,
    title: 'Sequence Models (Pre-Transformer)',
    slug: 'sequence-models',
    summary: 'Recurrent architectures, gating mechanisms, seq2seq models, and attention before transformers.',
    conceptCount: 10,
    range: [38, 47],
  },
  {
    number: 5,
    title: 'The Transformer',
    slug: 'transformer',
    summary: 'Self-attention, multi-head attention, positional encodings, and the full transformer architecture.',
    conceptCount: 18,
    range: [48, 65],
  },
  {
    number: 6,
    title: 'Training LLMs',
    slug: 'training',
    summary: 'Pre-training objectives, optimization, distributed training paradigms, and scaling laws.',
    conceptCount: 16,
    range: [66, 81],
  },
  {
    number: 7,
    title: 'Text Generation & Decoding',
    slug: 'text-generation',
    summary: 'Autoregressive generation loops, temperature, greedy decoding, beam search, and sampling methods.',
    conceptCount: 14,
    range: [82, 95],
  },
  {
    number: 8,
    title: 'Attention Visualizations',
    slug: 'attention-viz',
    summary: 'Heatmaps, attention patterns across layers and heads, attention sinks, and rollout dynamics.',
    conceptCount: 8,
    range: [96, 103],
  },
  {
    number: 9,
    title: 'Context & Memory',
    slug: 'context-memory',
    summary: 'KV cache management, sliding window attention, Flash Attention, and context extension methods.',
    conceptCount: 10,
    range: [104, 113],
  },
  {
    number: 10,
    title: 'Alignment & Safety',
    slug: 'alignment-safety',
    summary: 'SFT, RLHF, DPO, constitutional self-critique, red teaming, guardrails, and grounding.',
    conceptCount: 12,
    range: [114, 125],
  },
  {
    number: 11,
    title: 'Efficiency & Optimization',
    slug: 'efficiency-optimization',
    summary: 'Quantization, pruning, LoRA, QLoRA, adapter layers, model merging, and activation checkpointing.',
    conceptCount: 14,
    range: [126, 139],
  },
  {
    number: 12,
    title: 'Architecture Variants',
    slug: 'architecture-variants',
    summary: 'Mixture of Experts, state space models (Mamba), RWKV, Vision Transformers, and multimodal models.',
    conceptCount: 12,
    range: [140, 151],
  },
  {
    number: 13,
    title: 'RAG (Retrieval-Augmented Generation)',
    slug: 'rag',
    summary: 'Document chunking, vector embeddings, similarity search, HNSW, reranking, and evaluation.',
    conceptCount: 12,
    range: [152, 163],
  },
  {
    number: 14,
    title: 'Prompting & Usage',
    slug: 'prompting',
    summary: 'Prompt structures, zero-shot and few-shot prompting, Chain of Thought, ReAct, and prompt caching.',
    conceptCount: 14,
    range: [164, 177],
  },
  {
    number: 15,
    title: 'Agents & Multi-Step Reasoning',
    slug: 'agents',
    summary: 'Agent loops, tool orchestration, task decomposition, reflection, memory, and multi-agent coordination.',
    conceptCount: 10,
    range: [178, 187],
  },
  {
    number: 16,
    title: 'Evaluation & Benchmarks',
    slug: 'evaluation-benchmarks',
    summary: 'Perplexity, BLEU, ROUGE, benchmark leaderboards, ELO ratings, and calibration curves.',
    conceptCount: 10,
    range: [188, 197],
  },
  {
    number: 17,
    title: 'Infrastructure & Serving',
    slug: 'infrastructure-serving',
    summary: 'GPU architectures, continuous batching, memory breakdown, serving systems, and TTFT/TPOT latency.',
    conceptCount: 10,
    range: [198, 207],
  },
  {
    number: 18,
    title: 'Model Family Tree & History',
    slug: 'history',
    summary: 'Historical evolution from Word2Vec to modern frontier models, parameter growth, and emergent abilities.',
    conceptCount: 8,
    range: [208, 215],
  },
];
