import json
import re

categories = [
    {"num": 1, "name": "Neural Network Foundations", "slug": "neural-foundations"},
    {"num": 2, "name": "Text Representation", "slug": "text-representation"},
    {"num": 3, "name": "Tokenization in Detail", "slug": "tokenization"},
    {"num": 4, "name": "Sequence Models (Pre-Transformer)", "slug": "sequence-models"},
    {"num": 5, "name": "The Transformer", "slug": "transformer"},
    {"num": 6, "name": "Training LLMs", "slug": "training"},
    {"num": 7, "name": "Text Generation & Decoding", "slug": "text-generation"},
    {"num": 8, "name": "Attention Visualizations", "slug": "attention-viz"},
    {"num": 9, "name": "Context & Memory", "slug": "context-memory"},
    {"num": 10, "name": "Alignment & Safety", "slug": "alignment-safety"},
    {"num": 11, "name": "Efficiency & Optimization", "slug": "efficiency-optimization"},
    {"num": 12, "name": "Architecture Variants", "slug": "architecture-variants"},
    {"num": 13, "name": "RAG (Retrieval-Augmented Generation)", "slug": "rag"},
    {"num": 14, "name": "Prompting & Usage", "slug": "prompting"},
    {"num": 15, "name": "Agents & Multi-Step Reasoning", "slug": "agents"},
    {"num": 16, "name": "Evaluation & Benchmarks", "slug": "evaluation-benchmarks"},
    {"num": 17, "name": "Infrastructure & Serving", "slug": "infrastructure-serving"},
    {"num": 18, "name": "Model Family Tree & History", "slug": "history"},
]

cat_map = {c["num"]: c for c in categories}

# Table of 215 concepts from specification
concepts = [
    # Category 1: Neural Network Foundations (1-15)
    (1, 1, "Perceptron", "perceptron", "Beginner",
     "Single neuron computing a weighted sum followed by a threshold activation.",
     "The perceptron is the simplest artificial neuron architecture. It computes a linear combination of inputs and weights, adds a bias, and passes the result through an activation function.",
     "It forms the foundational computational unit of multi-layer neural networks and deep learning models.",
     ["Multiply each input value x_i by weight w_i.", "Sum all weighted inputs: z = sum(w_i * x_i) + b.", "Apply an activation function to generate the output."],
     "A perceptron computes a linear decision boundary in input space.",
     "The Perceptron: A Probabilistic Model for Information Storage and Organization in the Brain", "https://psycnet.apa.org/record/1959-09865-001", 1958, "Frank Rosenblatt"),

    (2, 1, "Activation Functions", "activation-functions", "Beginner",
     "Non-linear mathematical functions enabling neural networks to learn non-linear boundaries.",
     "Activation functions introduce non-linear mappings into neural network layers. Examples include ReLU, Sigmoid, Tanh, GELU, and Swish/SiLU.",
     "Without non-linearities, stacking multiple linear layers collapses mathematically into a single linear transformation.",
     ["Compute linear pre-activation value z = Wx + b.", "Apply non-linear function f(z), such as max(0, z) for ReLU.", "Forward the activated output to subsequent layers."],
     "Non-linear activation functions give deep neural networks the ability to approximate complex functions.",
     "Deep Learning", "https://www.deeplearningbook.org/", 2016, "Goodfellow, Bengio, Courville"),

    (3, 1, "Multi-Layer Perceptron", "multi-layer-perceptron", "Beginner",
     "Feedforward neural network with input, hidden, and output layers of interconnected neurons.",
     "A Multi-Layer Perceptron (MLP) consists of multiple fully connected layers of neurons where each layer transforms representations progressively.",
     "MLPs overcome the linear separability limitations of single perceptrons, solving problems like XOR.",
     ["Receive raw input features at the input layer.", "Pass activations through one or more hidden layers with non-linear functions.", "Compute final predictions at the output layer."],
     "Hidden layers allow neural networks to build hierarchical representations of data.",
     "Learning representations by back-propagating errors", "https://www.nature.com/articles/323533a0", 1986, "Rumelhart, Hinton, Williams"),

    (4, 1, "Forward Pass", "forward-pass", "Beginner",
     "Sequential calculation of layer outputs from input to prediction.",
     "The forward pass is the computational process where inputs propagate through network layers to produce predictions.",
     "It evaluates the model on input data and produces the predictions needed to calculate training loss.",
     ["Feed inputs into the first layer.", "Compute linear transformations and non-linear activations layer by layer.", "Store intermediate activations for use during backpropagation.", "Output final predictions from the last layer."],
     "The forward pass computes predictions and caches intermediate values for gradient updates.",
     "Deep Learning", "https://www.deeplearningbook.org/", 2016, "Goodfellow, Bengio, Courville"),

    (5, 1, "Loss Functions", "loss-functions", "Beginner",
     "Mathematical functions quantifying the difference between predictions and targets.",
     "A loss function computes a scalar penalty score measuring prediction errors. Common examples are Mean Squared Error (MSE) for regression and Cross-Entropy for classification.",
     "The loss function provides the scalar training objective that optimization algorithms minimize.",
     ["Compare predicted output y_hat with true label y.", "Calculate error using formulas like MSE: (y - y_hat)^2 or Cross-Entropy: -log(y_hat).", "Average loss values across the batch."],
     "Loss functions guide parameter updates by measuring model performance numerically.",
     "Deep Learning", "https://www.deeplearningbook.org/", 2016, "Goodfellow, Bengio, Courville"),

    (6, 1, "Backpropagation", "backpropagation", "Intermediate",
     "Application of the calculus chain rule to calculate loss gradients with respect to all weights.",
     "Backpropagation computes the partial derivatives of the loss function with respect to each model parameter by propagating gradients backward from output to input.",
     "It allows efficient gradient computation across millions or billions of parameters in deep architectures.",
     ["Compute loss on the forward pass output.", "Calculate loss derivative with respect to output logits.", "Iterate backward through layers using the chain rule to accumulate partial derivatives."],
     "Backpropagation applies the calculus chain rule to compute exact parameter gradients efficiently.",
     "Learning representations by back-propagating errors", "https://www.nature.com/articles/323533a0", 1986, "Rumelhart, Hinton, Williams"),

    (7, 1, "Gradient Descent", "gradient-descent", "Intermediate",
     "Iterative optimization algorithm updating parameters in the direction of steepest loss decrease.",
     "Gradient descent updates model weights proportionally to the negative gradient of the loss function.",
     "It is the core optimization engine used to train neural network parameters.",
     ["Calculate loss gradients with backpropagation.", "Multiply gradients by a learning rate factor.", "Subtract the result from current weights: theta = theta - lr * grad."],
     "Gradient descent navigates high-dimensional loss surfaces toward local or global minima.",
     "An overview of gradient descent optimization algorithms", "https://arxiv.org/abs/1609.04747", 2016, "Sebastian Ruder"),

    (8, 1, "Learning Rate", "learning-rate", "Beginner",
     "Hyperparameter controlling the step size during parameter optimization updates.",
     "The learning rate scales the magnitude of parameter updates at each optimization step.",
     "A rate set too high causes loss oscillation or divergence; a rate set too low leads to slow training.",
     ["Compute gradient of loss with respect to parameters.", "Scale gradient vector by learning rate scalar eta.", "Update weights: w_new = w_old - eta * grad."],
     "The learning rate is the most critical hyperparameter for stable neural network convergence.",
     "Deep Learning", "https://www.deeplearningbook.org/", 2016, "Goodfellow, Bengio, Courville"),

    (9, 1, "Overfitting & Underfitting", "overfitting-underfitting", "Beginner",
     "Balance between model memorization of training data and generalization to unseen validation data.",
     "Underfitting occurs when a model lacks capacity to capture patterns; overfitting occurs when a model memorizes noise in training data and fails on test data.",
     "Understanding this tradeoff ensures models generalize effectively to real-world inputs.",
     ["Track training loss and validation loss across training epochs.", "Detect underfitting when both training and validation losses remain high.", "Detect overfitting when training loss drops while validation loss begins rising."],
     "Optimal generalization occurs where validation loss reaches its minimum before divergence.",
     "Deep Learning", "https://www.deeplearningbook.org/", 2016, "Goodfellow, Bengio, Courville"),

    (10, 1, "Regularization", "regularization", "Intermediate",
     "Techniques including L1/L2 weight decay and Dropout to prevent overfitting.",
     "Regularization adds constraints or penalties to network training to discourage overly complex weights and improve generalization.",
     "It prevents models with large parameter counts from memorizing specific training samples.",
     ["L2 regularization (weight decay) adds sum of squared weights to the loss.", "L1 regularization adds sum of absolute weights, inducing parameter sparsity.", "Dropout randomly deactivates a subset of neurons during each training step."],
     "Regularization techniques constrain model capacity to achieve better validation generalization.",
     "Dropout: A Simple Way to Prevent Neural Networks from Overfitting", "https://jmlr.org/papers/v15/srivastava14a.html", 2014, "Srivastava et al."),

    (11, 1, "Batch Normalization", "batch-normalization", "Intermediate",
     "Layer normalization technique stabilizing internal covariate shift across mini-batches.",
     "Batch Normalization normalizes layer inputs across the mini-batch dimension to have zero mean and unit variance, followed by learned scale and shift parameters.",
     "It accelerates convergence, stabilizes gradients, and allows higher learning rates.",
     ["Calculate mini-batch mean and variance for layer activations.", "Normalize activations: x_hat = (x - mean) / sqrt(var + eps).", "Scale and shift using learnable parameters gamma and beta: y = gamma * x_hat + beta."],
     "Batch normalization stabilizes activation distributions throughout deep network architectures.",
     "Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift", "https://arxiv.org/abs/1502.03167", 2015, "Ioffe, Szegedy"),

    (12, 1, "Weight Initialization", "weight-initialization", "Intermediate",
     "Methods for setting starting weight distributions to avoid vanishing or exploding activations.",
     "Weight initialization schemes like Xavier/Glorot and He/Kaiming set initial random weights based on layer input and output dimensions.",
     "Poor initialization causes activations and gradients to collapse to zero or explode exponentially across layers.",
     ["Compute fan-in (number of input connections) and fan-out (number of output connections).", "Xavier: sample weights from normal distribution with variance 2 / (fan_in + fan_out).", "He: sample weights from normal distribution with variance 2 / fan_in for ReLU networks."],
     "Proper weight initialization preserves signal variance across deep layers during early training.",
     "Understanding the difficulty of training deep feedforward neural networks", "http://proceedings.mlr.press/v9/glorot10a.html", 2010, "Glorot, Bengio"),

    (13, 1, "Softmax", "softmax", "Beginner",
     "Mathematical function converting raw logit scores into normalized probability distributions.",
     "The softmax function exponentiates input logits and normalizes them so all elements sum to 1.0.",
     "It turns raw unconstrained network outputs into valid probability distributions for classification and token prediction.",
     ["Exponentiate each raw logit: exp(z_i).", "Sum all exponentiated values across the vector: sum(exp(z_j)).", "Divide each exponentiated value by the sum: p_i = exp(z_i) / sum(exp(z_j))."],
     "Softmax transforms arbitrary real-valued logits into a normalized probability distribution.",
     "Deep Learning", "https://www.deeplearningbook.org/", 2016, "Goodfellow, Bengio, Courville"),

    (14, 1, "Cross-Entropy Loss", "cross-entropy-loss", "Intermediate",
     "Loss metric measuring divergence between predicted probability distribution and true target labels.",
     "Cross-entropy measures the negative log-likelihood assigned by the model to the correct target class.",
     "It produces strong gradient signals when predictions are incorrect and scales naturally with probability outputs.",
     ["Compute softmax probability distribution over vocabulary or classes.", "Identify target index y.", "Calculate loss: L = -log(p_y)."],
     "Cross-entropy penalizes confident wrong predictions heavily, driving rapid probabilistic learning.",
     "Deep Learning", "https://www.deeplearningbook.org/", 2016, "Goodfellow, Bengio, Courville"),

    (15, 1, "Computation Graphs", "computation-graphs", "Advanced",
     "Directed acyclic graph of mathematical operations enabling automatic differentiation.",
     "A computation graph represents mathematical operations as nodes and tensors as edges in a directed acyclic graph (DAG).",
     "It allows automatic differentiation engines like PyTorch Autograd to track operations and calculate gradients automatically.",
     ["Record each mathematical operation during the forward pass.", "Construct dependency edges between tensors and operations.", "Traverse graph in topological reverse order during backward pass to apply chain rule."],
     "Computation graphs automate gradient derivation across arbitrary complex architectures.",
     "Automatic differentiation in PyTorch", "https://openreview.net/forum?id=BJJsrmfCZ", 2017, "Paszke et al."),

    # Category 2: Text Representation (16-27)
    (16, 2, "One-Hot Encoding", "one-hot-encoding", "Beginner",
     "Sparse vector representation where exactly one position is marked 1 and all others 0.",
     "One-hot encoding represents each word in a vocabulary as a sparse binary vector of length V containing a single 1 at the word index.",
     "It serves as the basic categorical representation before dense vector embeddings.",
     ["Assign unique integer index to each word in vocabulary.", "Create vector of length V filled with zeros.", "Set entry at the target word index to 1."],
     "One-hot vectors treat all words as orthogonal and equidistant, capturing no semantic relationships.",
     "Speech and Language Processing", "https://web.stanford.edu/~jurafsky/slp3/", 2024, "Jurafsky, Martin"),

    (17, 2, "Bag of Words", "bag-of-words", "Beginner",
     "Representation of text as word frequency counts ignoring grammar and word order.",
     "Bag of Words represents documents as histograms of word occurrences across the vocabulary.",
     "It provides a simple baseline feature representation for document classification.",
     ["Tokenize document into individual words.", "Count frequency of each vocabulary term.", "Store counts in a fixed-length vector across vocabulary."],
     "Bag of Words measures term frequency but completely discards sequential context and word order.",
     "Speech and Language Processing", "https://web.stanford.edu/~jurafsky/slp3/", 2024, "Jurafsky, Martin"),

    (18, 2, "TF-IDF", "tf-idf", "Beginner",
     "Term frequency weighted by inverse document frequency to highlight informative words.",
     "TF-IDF scales term frequency by how rare the term is across the entire corpus of documents.",
     "Common words like 'the' receive low weights while rare, informative words receive high scores.",
     ["Compute term frequency TF(t, d) within document d.", "Compute inverse document frequency IDF(t) = log(N / df(t)).", "Multiply TF * IDF to generate final feature weight."],
     "TF-IDF balances local term repetition against global term uniqueness.",
     "A Statistical Interpretation of Term Specificity and Its Application in Retrieval", "https://doi.org/10.1108/eb026526", 1972, "Karen Sparck Jones"),

    (19, 2, "Word2Vec (CBOW)", "word2vec-cbow", "Intermediate",
     "Continuous Bag of Words architecture predicting a center word from its context words.",
     "CBOW averages context word vectors within a sliding window to predict the probability of the center word.",
     "It enables neural models to learn dense semantic word embeddings from unannotated text corpora.",
     ["Extract context words within window of radius c around target.", "Average the embedding vectors of context words.", "Project average through output weight matrix to predict center word."],
     "CBOW learns fast distributed representations by predicting target tokens from surrounding context.",
     "Efficient Estimation of Word Representations in Vector Space", "https://arxiv.org/abs/1301.3781", 2013, "Mikolov et al."),

    (20, 2, "Word2Vec (Skip-gram)", "word2vec-skip-gram", "Intermediate",
     "Architecture predicting surrounding context words given a single center word.",
     "Skip-gram takes a single target word and maximizes the log probability of observing surrounding context words.",
     "It excels at representing rare words accurately compared to frequency-averaged methods.",
     ["Input center word token into embedding layer.", "Generate predictions for words appearing within context window.", "Apply negative sampling to optimize cross-entropy loss efficiently."],
     "Skip-gram learns robust semantic vectors by using single words to predict multi-word contexts.",
     "Distributed Representations of Words and Phrases and their Compositionality", "https://arxiv.org/abs/1310.4546", 2013, "Mikolov et al."),

    (21, 2, "GloVe", "glove", "Intermediate",
     "Global Vectors model learning word embeddings via matrix factorization of co-occurrence statistics.",
     "GloVe constructs a global word co-occurrence matrix and trains log-bilinear embeddings that encode ratios of co-occurrence probabilities.",
     "It combines the global statistical advantages of matrix factorization with the local window advantages of Word2Vec.",
     ["Count global co-occurrence frequencies X_ij across corpus.", "Formulate objective: sum f(X_ij) * (w_i^T * w_j + b_i + b_j - log(X_ij))^2.", "Optimize embeddings using stochastic gradient updates."],
     "GloVe maps global corpus co-occurrence statistics directly into linear vector sub-spaces.",
     "GloVe: Global Vectors for Word Representation", "https://nlp.stanford.edu/pubs/glove.pdf", 2014, "Pennington, Socher, Manning"),

    (22, 2, "Word Analogies", "word-analogies", "Beginner",
     "Vector arithmetic capturing linear semantic and syntactic relations between concepts.",
     "Word analogies demonstrate that geometric vector differences correspond to conceptual relationships like king - man + woman = queen.",
     "It reveals that dense embeddings organize semantic relations as consistent spatial translations.",
     ["Compute difference vector between pair: v(king) - v(man).", "Add vector of second concept: + v(woman).", "Locate nearest neighboring word vector in embedding space (queen)."],
     "Vector arithmetic in embedding spaces captures linear semantic analogies naturally.",
     "Linguistic Regularities in Continuous Space Word Representations", "https://aclanthology.org/N13-1090/", 2013, "Mikolov, Yih, Zweig"),

    (23, 2, "Cosine Similarity", "cosine-similarity", "Beginner",
     "Metric measuring the cosine of the angle between two vectors regardless of magnitude.",
     "Cosine similarity evaluates how closely two directional vectors point in the same direction, scaling from -1.0 to 1.0.",
     "It compares semantic similarity independently of vector length or document size.",
     ["Compute dot product between vectors A and B: A . B.", "Compute L2 norms ||A|| and ||B||.", "Calculate similarity: cos(theta) = (A . B) / (||A|| * ||B||)."],
     "Cosine similarity focuses on directional alignment rather than vector magnitude.",
     "Speech and Language Processing", "https://web.stanford.edu/~jurafsky/slp3/", 2024, "Jurafsky, Martin"),

    (24, 2, "Embedding Dimensions", "embedding-dimensions", "Intermediate",
     "Tradeoff between representation capacity, geometric separation, and computational efficiency.",
     "Embedding dimensions determine how many continuous coordinates are used to represent each semantic token.",
     "Higher dimensions capture finer distinctions and reduce geometric crowding, but increase memory and compute.",
     ["Map words to d-dimensional coordinate vectors.", "Observe geometric clustering in 2D vs 50D vs 300D vs 1536D.", "Measure similarity separation and crowding effect."],
     "Higher embedding dimensions resolve semantic nuance at the cost of memory and computation.",
     "Deep Learning", "https://www.deeplearningbook.org/", 2016, "Goodfellow, Bengio, Courville"),

    (25, 2, "Sentence Embeddings", "sentence-embeddings", "Intermediate",
     "Techniques for aggregating token embeddings into fixed-size sentence and document vectors.",
     "Sentence embeddings condense entire variable-length sentences into a single dense vector using mean pooling, max pooling, or CLS token representations.",
     "They enable semantic search, document deduplication, and clustering across text collections.",
     ["Pass sentence tokens through encoder layers.", "Apply pooling strategy across token output vectors.", "Normalize sentence vector for downstream similarity evaluation."],
     "Sentence embeddings compress variable-length token sequences into fixed-dimensional semantic vectors.",
     "Sentence-BERT: Sentence Embeddings using Siamese BERT-Networks", "https://arxiv.org/abs/1908.10084", 2019, "Reimers, Gurevych"),

    (26, 2, "Embedding Lookup Table", "embedding-lookup-table", "Beginner",
     "Matrix mapping discrete token integer IDs directly to continuous dense vectors.",
     "An embedding lookup table is a weight matrix of size V x d where integer token IDs act as row indices.",
     "It provides the initial translation from discrete vocabulary symbols into continuous neural space.",
     ["Receive integer token index i.", "Index directly into row i of embedding matrix W_emb.", "Pass retrieved row vector of length d to the first model layer."],
     "Embedding lookup is equivalent to multiplying a one-hot vector by the embedding weight matrix.",
     "Attention Is All You Need", "https://arxiv.org/abs/1706.03762", 2017, "Vaswani et al."),

    (27, 2, "Embedding Space Explorer", "embedding-space-explorer", "Beginner",
     "Visual exploration of high-dimensional semantic spaces projected down to 3D.",
     "Dimensionality reduction algorithms like t-SNE and UMAP project high-dimensional word vectors into 3D for interactive spatial inspection.",
     "It illustrates how semantic categories and syntactic clusters organize geometrically.",
     ["Project high-dimensional word vectors to 3D coordinates.", "Cluster words by semantic category and part of speech.", "Explore nearest neighbors and spatial neighborhoods interactively."],
     "Geometric distance in projected embedding spaces reflects conceptual similarity.",
     "Visualizing Data using t-SNE", "https://jmlr.org/papers/v9/vandermaaten08a.html", 2008, "Van der Maaten, Hinton"),

    # Category 3: Tokenization in Detail (28-37)
    (28, 3, "Character-Level Tokenization", "character-level", "Beginner",
     "Splitting input text into individual unicode characters or single bytes.",
     "Character-level tokenization parses text into individual characters, maintaining a small vocabulary size (e.g. 256 for bytes) without out-of-vocabulary words.",
     "It eliminates out-of-vocabulary issues but produces long sequence lengths that increase attention computation.",
     ["Receive input text string.", "Split string into array of single characters.", "Map each character to its unique integer ID."],
     "Character-level tokenization eliminates unknown words at the cost of long sequence lengths.",
     "Speech and Language Processing", "https://web.stanford.edu/~jurafsky/slp3/", 2024, "Jurafsky, Martin"),

    (29, 3, "Word-Level Tokenization", "word-level", "Beginner",
     "Splitting text by whitespace and punctuation into discrete whole-word tokens.",
     "Word-level tokenization splits text on whitespace and punctuation marks, treating each distinct word as a separate vocabulary item.",
     "It creates short sequence lengths but suffers from huge vocabulary requirements and out-of-vocabulary (OOV) tokens.",
     ["Split input text by whitespace delimiters.", "Separate punctuation from alphanumeric words.", "Lookup each word in vocabulary dictionary, returning [UNK] if absent."],
     "Word tokenization preserves full word semantics but fails when encountering unseen vocabulary.",
     "Speech and Language Processing", "https://web.stanford.edu/~jurafsky/slp3/", 2024, "Jurafsky, Martin"),

    (30, 3, "Byte Pair Encoding (BPE)", "bpe", "Intermediate",
     "Subword tokenization iteratively merging the most frequent adjacent character pairs.",
     "Byte Pair Encoding (BPE) starts with a character vocabulary and iteratively merges the most frequent adjacent symbol pairs in the training corpus into subwords.",
     "It balances vocabulary size against sequence length, handling common words as single tokens and rare words as subwords.",
     ["Initialize vocabulary with base characters.", "Count frequencies of all adjacent token pairs in corpus.", "Merge highest frequency pair into new token and repeat until target vocabulary size."],
     "BPE builds compact subword vocabularies by merging frequent character sequences iteratively.",
     "Neural Machine Translation of Rare Words with Subword Units", "https://arxiv.org/abs/1508.07909", 2016, "Sennrich, Haddow, Birch"),

    (31, 3, "WordPiece", "wordpiece", "Intermediate",
     "Likelihood-based subword algorithm used in BERT with continuity prefixes like ##.",
     "WordPiece selects subword merges based on maximum likelihood on training data rather than raw frequency count.",
     "It identifies subwords that maximize training text probability and marks continuation subwords with prefixes like '##'.",
     ["Initialize base vocabulary with characters and special tokens.", "Evaluate candidates based on likelihood gain: score = freq(AB) / (freq(A) * freq(B)).", "Add top scoring merge and repeat."],
     "WordPiece optimizes corpus likelihood to select meaningful morphological subword segments.",
     "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding", "https://arxiv.org/abs/1810.04805", 2018, "Devlin et al."),

    (32, 3, "SentencePiece & Unigram", "sentencepiece-unigram", "Advanced",
     "Probabilistic subword tokenization pruning candidates from a large initial pool.",
     "The Unigram model starts with a large candidate vocabulary and iteratively removes tokens that minimize the loss in training corpus likelihood.",
     "It treats whitespace as a regular character (e.g. _) and enables subword regularization during training.",
     ["Generate large initial seed vocabulary of words and frequent substrings.", "Compute unigram occurrence probabilities for all tokens.", "Prune the lowest-impact percentage of tokens iteratively."],
     "Unigram tokenization finds optimal probabilistic subword segmentation without language-specific pre-tokenization.",
     "Subword Regularization: Improving Neural Network Translation Models with Multiple Subword Candidates", "https://arxiv.org/abs/1804.10959", 2018, "Taku Kudo"),

    (33, 3, "Tokenizer Comparison", "tokenizer-comparison", "Beginner",
     "Side-by-side comparison of tiktoken, WordPiece, and SentencePiece token counts.",
     "Different tokenizers use distinct vocabularies and splitting rules, leading to different token counts and boundaries for identical input text.",
     "Token counts directly affect inference latency, context window utilization, and billing cost.",
     ["Feed identical text string into GPT-4 (tiktoken), BERT (WordPiece), and LLaMA (SentencePiece).", "Inspect resulting token lists and boundaries.", "Compare total token counts and compression ratios."],
     "Modern byte-level BPE tokenizers achieve superior compression ratios across code and text.",
     "Language Models are Few-Shot Learners", "https://arxiv.org/abs/2005.14165", 2020, "Brown et al."),

    (34, 3, "Special Tokens", "special-tokens", "Beginner",
     "Control symbols like [CLS], [SEP], [PAD], [MASK], and end-of-text markers.",
     "Special tokens are reserved vocabulary entries indicating structural boundaries, sequence roles, or training masking.",
     "They signal prompt endings, separate multi-turn dialogue roles, and denote classification anchors.",
     ["Prepend [CLS] or <s> at sequence start for pooled classification.", "Insert [SEP] or </s> between sentence pairs.", "Append <|endoftext|> or <|eot_id|> when text generation concludes."],
     "Special tokens provide architectural control cues to language models.",
     "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding", "https://arxiv.org/abs/1810.04805", 2018, "Devlin et al."),

    (35, 3, "Vocabulary & Token IDs", "vocabulary-token-ids", "Beginner",
     "Bidirectional mapping between string subwords and integer IDs.",
     "The vocabulary dictionary maps each textual token string to an exact integer ID and vice-versa.",
     "Neural network embedding layers require non-negative integer indices as inputs.",
     ["Segment input string into subword pieces.", "Query vocabulary lookup table to fetch corresponding integer ID for each piece.", "Pass integer ID array to the model embedding layer."],
     "Vocabulary tables convert human text into discrete integer sequences for neural processing.",
     "Attention Is All You Need", "https://arxiv.org/abs/1706.03762", 2017, "Vaswani et al."),

    (36, 3, "Detokenization", "detokenization", "Beginner",
     "Reconstructing natural text strings from sequences of token IDs.",
     "Detokenization maps predicted integer token IDs back into string fragments and concatenates them into natural human text.",
     "It cleans up subword prefixes (such as '##' or byte sequences) and restores proper spacing.",
     ["Lookup string corresponding to each token ID.", "Join fragments together.", "Decode byte sequences into valid UTF-8 characters."],
     "Detokenization restores original whitespace and character casing from model output IDs.",
     "Speech and Language Processing", "https://web.stanford.edu/~jurafsky/slp3/", 2024, "Jurafsky, Martin"),

    (37, 3, "Multilingual Tokenization", "multilingual-tokenization", "Intermediate",
     "Token compression disparities across non-Latin scripts and low-resource languages.",
     "Tokenizers trained primarily on English text require significantly more tokens per sentence when processing languages like Chinese, Arabic, or Hindi.",
     "High token counts increase context window consumption and latency for multilingual users.",
     ["Tokenize identical semantic text translated across English, Arabic, and Hindi.", "Count tokens required for each language.", "Observe how byte fallback fragments non-Latin characters into multiple sub-byte tokens."],
     "Multilingual vocabularies require dedicated non-Latin token coverage to ensure equitable efficiency.",
     "LLaMA: Open and Efficient Foundation Language Models", "https://arxiv.org/abs/2302.13971", 2023, "Touvron et al."),

    # Category 4: Sequence Models, Pre-Transformer (38-47)
    (38, 4, "RNN (Recurrent Neural Network)", "rnn", "Intermediate",
     "Recurrent architecture maintaining a persistent hidden state across sequential time steps.",
     "Recurrent Neural Networks (RNNs) process tokens sequentially, passing an updated hidden state vector h_t = tanh(W_h * h_{t-1} + W_x * x_t + b) from one time step to the next.",
     "They introduced sequence processing capability into deep learning before attention mechanisms.",
     ["Receive current token input x_t and previous hidden state h_{t-1}.", "Compute new hidden state combining input and memory.", "Produce step output y_t and pass h_t forward."],
     "Standard RNNs suffer from vanishing and exploding gradients over long sequence lengths.",
     "Learning representations by back-propagating errors", "https://www.nature.com/articles/323533a0", 1986, "Rumelhart, Hinton, Williams"),

    (39, 4, "Vanishing Gradients", "vanishing-gradients", "Intermediate",
     "Exponential decay of backpropagated gradient magnitudes through unrolled sequence steps.",
     "When backpropagating through time, multiplying many weight matrices and derivative terms smaller than 1 causes gradients to shrink exponentially toward zero.",
     "It prevents standard RNNs from learning long-range dependencies across distant sequence tokens.",
     ["Perform backpropagation through time over T steps.", "Multiply Jacobians across all intermediate transitions.", "Observe gradient magnitudes decaying toward zero at early tokens."],
     "Vanishing gradients restrict standard recurrent networks to short-range memory.",
     "Gradient Flow in Recurrent Nets: the Difficulty of Learning Long-Term Dependencies", "http://people.idsia.ch/~juergen/SeppHochreiter1991ThesisAbstract.html", 1991, "Sepp Hochreiter"),

    (40, 4, "Exploding Gradients", "exploding-gradients", "Intermediate",
     "Exponential amplification of gradients leading to numerical overflow and divergence.",
     "When weight eigenvalues exceed 1, repeated matrix multiplication during backpropagation through time causes gradients to grow exponentially.",
     "It causes catastrophic training divergence and numerical instability.",
     ["Track gradient norms during backpropagation.", "Detect exponential growth exceeding numerical limits.", "Apply gradient clipping by rescaling gradient vector if norm exceeds threshold."],
     "Gradient clipping stabilizes training by placing an upper bound on parameter update magnitudes.",
     "On the difficulty of training recurrent neural networks", "https://arxiv.org/abs/1211.5063", 2013, "Pascanu, Mikolov, Bengio"),

    (41, 4, "LSTM (Long Short-Term Memory)", "lstm", "Intermediate",
     "Gated recurrent architecture with forget, input, and output gates protecting a cell state highway.",
     "LSTM networks use dedicated gating mechanisms (forget gate, input gate, output gate) to regulate information flow into and out of an explicit cell state vector C_t.",
     "The additive linear cell state highway allows error gradients to backpropagate across hundreds of time steps without vanishing.",
     ["Compute forget gate: f_t = sigma(W_f * [h_{t-1}, x_t] + b_f).", "Compute candidate cell update and input gate: i_t.", "Update cell state: C_t = f_t * C_{t-1} + i_t * C_tilde_t.", "Compute output gate and hidden state: h_t = o_t * tanh(C_t)."],
     "LSTMs overcome vanishing gradients by providing an additive constant error carousel for memory.",
     "Long Short-Term Memory", "https://www.mitpressjournals.org/doi/abs/10.1162/neco.1997.9.8.1735", 1997, "Hochreiter, Schmidhuber"),

    (42, 4, "GRU (Gated Recurrent Unit)", "gru", "Intermediate",
     "Streamlined recurrent cell combining forget and input gates into a single update gate.",
     "The Gated Recurrent Unit (GRU) merges the cell state and hidden state, using only reset and update gates to control memory retention.",
     "It achieves performance comparable to LSTM with fewer parameters and faster training.",
     ["Compute reset gate r_t controlling how much past state to ignore.", "Compute update gate z_t balancing past memory against candidate activation.", "Calculate new hidden state h_t as linear interpolation between previous state and candidate."],
     "GRUs provide gated memory retention with lower computational complexity than LSTMs.",
     "Empirical Evaluation of Gated Recurrent Neural Networks on Sequence Modeling", "https://arxiv.org/abs/1412.3555", 2014, "Chung et al."),

    (43, 4, "Bidirectional RNN", "bidirectional-rnn", "Intermediate",
     "Dual recurrent networks processing sequences forward and backward simultaneously.",
     "Bidirectional RNNs run one recurrent layer from left-to-right and a second layer from right-to-left, concatenating hidden representations at each position.",
     "They provide context from both preceding and succeeding tokens for tasks like named entity recognition and POS tagging.",
     ["Pass sequence through forward RNN (left to right).", "Pass sequence through backward RNN (right to left).", "Concatenate [h_forward, h_backward] at each position."],
     "Bidirectional processing captures full bidirectional sequence context for non-autoregressive tasks.",
     "Bidirectional Recurrent Neural Networks", "https://ieeexplore.ieee.org/document/650093", 1997, "Schuster, Paliwal"),

    (44, 4, "Seq2Seq (Encoder-Decoder)", "seq2seq", "Intermediate",
     "Architecture mapping variable-length input sequences to variable-length outputs via a bottleneck.",
     "Sequence-to-Sequence models encode an input sequence into a fixed-length context vector, which a decoder network unpacks into an output sequence.",
     "It established modern neural machine translation and sequence transduction architectures.",
     ["Encoder RNN processes input tokens and produces final summary vector h_T.", "Decoder RNN is initialized with h_T as its starting state.", "Decoder generates output tokens autoregressively until end-of-sequence."],
     "The fixed-size context vector creates an information bottleneck for long input sequences.",
     "Sequence to Sequence Learning with Neural Networks", "https://arxiv.org/abs/1409.3215", 2014, "Sutskever, Vinyals, Le"),

    (45, 4, "Attention (Bahdanau)", "attention-bahdanau", "Intermediate",
     "Additive alignment mechanism allowing decoders to query all encoder hidden states directly.",
     "Bahdanau attention calculates dynamic alignment weights between the current decoder state and all encoder hidden states, creating a weighted context vector for each step.",
     "It broke the fixed-length vector bottleneck in Seq2Seq models and paved the way for transformers.",
     ["Compute alignment scores: score(s_{i-1}, h_j) = v_a^T * tanh(W_a * s_{i-1} + U_a * h_j).", "Apply softmax across input sequence to obtain attention distribution alpha_ij.", "Compute context vector c_i as weighted sum of encoder hidden states: sum(alpha_ij * h_j)."],
     "Attention eliminates the fixed bottleneck by allowing direct access to all past encoder representations.",
     "Neural Machine Translation by Jointly Learning to Align and Translate", "https://arxiv.org/abs/1409.0473", 2014, "Bahdanau, Cho, Bengio"),

    (46, 4, "Teacher Forcing", "teacher-forcing", "Advanced",
     "Training strategy feeding ground-truth prior tokens to decoders rather than model predictions.",
     "Teacher forcing supplies the ground-truth target token from step t-1 as the decoder input at step t during training, rather than the model's own sampled prediction.",
     "It accelerates training convergence and stabilizes early learning trajectories.",
     ["At step t, feed ground-truth token y_{t-1}^* as decoder input.", "Compute cross-entropy loss against target token y_t^*.", "Address exposure bias during inference where true tokens are unavailable."],
     "Teacher forcing enables fast parallel training but causes exposure bias during autonomous inference.",
     "A Learning Algorithm for Continually Running Fully Recurrent Neural Networks", "https://doi.org/10.1162/neco.1989.1.2.270", 1989, "Williams, Zipser"),

    (47, 4, "Why Transformers Won", "why-transformers-won", "Beginner",
     "Comparison of sequential recurrent bottlenecks versus parallel self-attention computation.",
     "Transformers replaced recurrent step-by-step sequential processing with parallel self-attention across the entire sequence length at once.",
     "Parallel execution allows transformers to fully utilize modern GPU tensor hardware, scaling efficiently to massive training datasets.",
     ["Compare RNN sequential computation O(n) steps with Transformer O(1) sequential operations.", "Observe GPU utilization differences during forward and backward passes.", "Analyze maximum path length for gradient flow: O(n) in RNN vs O(1) in Transformer."],
     "Transformers won because parallel attention scales with modern hardware while recurrent models bottleneck sequentially.",
     "Attention Is All You Need", "https://arxiv.org/abs/1706.03762", 2017, "Vaswani et al."),

    # Category 5: The Transformer (48-65)
    (48, 5, "Transformer Architecture (Full)", "transformer-architecture", "Intermediate",
     "Complete encoder-decoder architecture built entirely on self-attention and feed-forward layers.",
     "The Transformer architecture comprises stacked encoder and decoder blocks featuring multi-head self-attention, position-wise feed-forward networks, residual connections, and layer normalization.",
     "It serves as the foundational architecture for all modern large language models.",
     ["Pass token embeddings plus positional encodings into encoder stack.", "Encoder computes bidirectional self-attention and feed-forward transformations.", "Decoder consumes target tokens with causal masking and performs cross-attention over encoder outputs."],
     "The Transformer replaces recurrence completely with attention, enabling massive parallelism.",
     "Attention Is All You Need", "https://arxiv.org/abs/1706.03762", 2017, "Vaswani et al."),

    (49, 5, "Self-Attention", "self-attention", "Intermediate",
     "Mechanism allowing every token in a sequence to attend to and aggregate every other token.",
     "Self-attention calculates pairwise compatibility weights between all positions in a sequence, updating each token representation with a weighted mixture of all other tokens.",
     "It captures contextual dependencies regardless of distance between tokens in O(1) operation path length.",
     ["Project input vectors into Query (Q), Key (K), and Value (V) tensors.", "Calculate pairwise similarity scores between Q and K.", "Apply softmax and compute weighted sum of V."],
     "Self-attention creates contextualized representations by blending token values based on query-key relevance.",
     "Attention Is All You Need", "https://arxiv.org/abs/1706.03762", 2017, "Vaswani et al."),

    (50, 5, "Key, Query, Value", "key-query-value", "Intermediate",
     "Triad of linear projections mapping embeddings into search queries, matching keys, and content values.",
     "Each token embedding is projected via learned linear matrices into a Query vector ('what am I seeking?'), a Key vector ('what do I offer?'), and a Value vector ('what is my content?').",
     "This formulation models attention as a continuous differentiable database lookup.",
     ["Multiply token embedding x_i by weight matrices W_Q, W_K, W_V.", "Match query q_i against key k_j to calculate relevance weight.", "Retrieve and scale value vector v_j according to computed weight."],
     "Queries match keys to determine how much of each value vector to retrieve.",
     "Attention Is All You Need", "https://arxiv.org/abs/1706.03762", 2017, "Vaswani et al."),

    (51, 5, "Scaled Dot-Product Attention", "scaled-dot-product-attention", "Advanced",
     "Exact mathematical formulation: Attention(Q, K, V) = softmax(Q * K^T / sqrt(d_k)) * V.",
     "Scaled dot-product attention multiplies Query and transposed Key matrices, divides by the square root of key dimension d_k to prevent gradient vanishing in softmax, and multiplies by Value matrix V.",
     "It provides the core numerical operation executed billions of times inside transformer blocks.",
     ["Compute raw attention scores: S = Q * K^T.", "Scale scores by dividing by sqrt(d_k): S_scaled = S / sqrt(d_k).", "Compute attention weights: A = softmax(S_scaled).", "Compute output representations: O = A * V."],
     "Dividing by sqrt(d_k) keeps dot products in regions with healthy softmax gradients.",
     "Attention Is All You Need", "https://arxiv.org/abs/1706.03762", 2017, "Vaswani et al."),

    (52, 5, "Multi-Head Attention", "multi-head-attention", "Intermediate",
     "Parallel attention heads allowing the model to attend to information at different positions and subspaces.",
     "Multi-Head Attention projects Q, K, and V into h distinct low-dimensional subspaces, computes scaled dot-product attention in parallel for each head, and concatenates the outputs.",
     "It allows the model to simultaneously attend to syntactic, semantic, and positional relationships.",
     ["Project Q, K, V into h distinct heads with dimension d_k = d_model / h.", "Execute scaled dot-product attention independently on each head.", "Concatenate all head outputs and project with linear matrix W_O."],
     "Multiple attention heads capture diverse contextual relationship patterns simultaneously.",
     "Attention Is All You Need", "https://arxiv.org/abs/1706.03762", 2017, "Vaswani et al."),

    (53, 5, "Attention Heads (What They Learn)", "attention-heads-what-they-learn", "Intermediate",
     "Empirical specialization of attention heads for syntax, coreference, punctuation, and positional proximity.",
     "Trained transformer heads naturally specialize in distinct linguistic patterns: some track previous/next tokens, others link verbs to objects, and others resolve pronoun coreferences.",
     "Understanding head roles provides insight into internal representations and model interpretability.",
     ["Extract attention matrices from trained multi-layer models.", "Identify positional heads with high diagonal weights.", "Identify syntactic heads linking pronouns (e.g. 'it') to their antecedent nouns."],
     "Different heads learn distinct syntactic and semantic roles without explicit supervision.",
     "What Does BERT Look At? An Analysis of BERT's Attention", "https://arxiv.org/abs/1906.04341", 2019, "Clark et al."),

    (54, 5, "Positional Encoding (Sinusoidal)", "positional-encoding-sinusoidal", "Intermediate",
     "Deterministic sine and cosine wave functions encoding sequence token positions.",
     "Sinusoidal positional encodings add fixed geometric vectors calculated from sine and cosine functions of varying frequencies to initial token embeddings.",
     "Since self-attention is permutation-invariant, positional encodings provide essential ordering information.",
     ["For position pos and dimension 2i: PE(pos, 2i) = sin(pos / 10000^(2i / d_model)).", "For dimension 2i+1: PE(pos, 2i+1) = cos(pos / 10000^(2i / d_model)).", "Add PE vector directly to token embedding before layer 1."],
     "Sinusoidal encodings allow models to generalize to arbitrary sequence lengths via linear trigonometric relations.",
     "Attention Is All You Need", "https://arxiv.org/abs/1706.03762", 2017, "Vaswani et al."),

    (55, 5, "Rotary Position Embeddings (RoPE)", "rope", "Advanced",
     "Relative positional encoding rotating Query and Key vectors in 2D coordinate planes.",
     "RoPE encodes relative token distances by applying a 2D rotation matrix to paired dimensions of Query and Key vectors before computing attention scores.",
     "It naturally decays attention strength with token distance and is standard in modern frontier LLMs like LLaMA and Mistral.",
     ["Split d-dimensional query and key vectors into d/2 two-dimensional pairs.", "Rotate each pair by angle m * theta_i proportional to token position m.", "Compute standard dot product: q_m^T * k_n depends strictly on relative offset (m - n)."],
     "RoPE incorporates relative distance into dot products via complex coordinate rotation.",
     "RoFormer: Enhanced Transformer with Rotary Position Embedding", "https://arxiv.org/abs/2104.09864", 2021, "Su et al."),

    (56, 5, "ALiBi", "alibi", "Advanced",
     "Attention with Linear Biases penalizing attention scores based on query-key token distance.",
     "ALiBi removes positional embeddings entirely and adds a non-learned static linear penalty proportional to distance |i - j| directly to the attention matrix.",
     "It enables transformers to extrapolate to sequences longer than those seen during training.",
     ["Compute standard dot product query-key matrix: Q * K^T / sqrt(d_k).", "Construct distance matrix: -m * |i - j| where m is head-specific slope.", "Add penalty matrix directly before softmax."],
     "ALiBi provides robust length extrapolation by biasing attention linearly by token distance.",
     "Train Short, Test Long: Attention with Linear Biases Enables Input Length Extrapolation", "https://arxiv.org/abs/2108.12409", 2021, "Press, Smith, Lewis"),

    (57, 5, "Residual Connections", "residual-connections", "Intermediate",
     "Skip connections adding layer inputs directly to outputs: x + Sublayer(x).",
     "Residual connections bypass non-linear sublayers, adding the input tensor directly to the sublayer output.",
     "They prevent gradient degradation, allowing training of hundreds of stacked transformer layers without vanishing gradients.",
     ["Pass tensor x through attention or feed-forward sublayer.", "Add identity shortcut: y = x + Sublayer(x).", "Apply layer normalization to combined sum."],
     "Skip connections create an uninterrupted gradient highway through deep architectures.",
     "Deep Residual Learning for Image Recognition", "https://arxiv.org/abs/1512.03385", 2015, "He et al."),

    (58, 5, "Layer Normalization", "layer-normalization", "Intermediate",
     "Normalizing activations across hidden feature dimensions per token: Pre-LN vs Post-LN.",
     "Layer Normalization computes mean and variance across the feature dimension for each individual token.",
     "Pre-LN (normalizing before the sublayer) provides superior gradient stability during deep LLM training compared to original Post-LN.",
     ["Calculate mean mu and variance sigma^2 across feature dimension d_model.", "Normalize: x_hat = (x - mu) / sqrt(sigma^2 + eps).", "Scale and shift with learnable parameters: LN(x) = gamma * x_hat + beta."],
     "Pre-LN stabilizes deep transformer training without requiring delicate learning rate warmups.",
     "Layer Normalization", "https://arxiv.org/abs/1607.06450", 2016, "Ba, Kiros, Hinton"),

    (59, 5, "Feed-Forward Network", "feed-forward-network", "Intermediate",
     "Position-wise two-layer MLP expanding hidden dimension from d_model to 4*d_model and back.",
     "The position-wise Feed-Forward Network (FFN) applies two linear transformations with a non-linear activation (GELU or SwiGLU) independently to every token position.",
     "It stores factual and linguistic knowledge associations learned during pre-training.",
     ["Project token vector from d_model to expanded dimension 4 * d_model.", "Apply non-linear activation like GELU or Swish.", "Contract representation back to d_model."],
     "Feed-forward layers act as key-value associative memories storing knowledge in transformer weights.",
     "Transformer Feed-Forward Layers Are Key-Value Memories", "https://arxiv.org/abs/2012.14913", 2020, "Geva et al."),

    (60, 5, "Causal Masking", "causal-masking", "Intermediate",
     "Lower-triangular attention mask preventing tokens from attending to future positions.",
     "Causal masking sets all attention matrix entries where position j > i to negative infinity prior to softmax, ensuring future token attention weights equal zero.",
     "It enforces autoregressive causality, ensuring the model only predicts based on preceding context.",
     ["Construct square attention score matrix of size N x N.", "Set upper triangular entries (j > i) to -1e9.", "Apply softmax, causing future position probabilities to become exactly zero."],
     "Causal masking prevents information leakage from future tokens during autoregressive text generation.",
     "Attention Is All You Need", "https://arxiv.org/abs/1706.03762", 2017, "Vaswani et al."),

    (61, 5, "Padding Mask", "padding-mask", "Intermediate",
     "Masking out padding tokens in variable-length batches to prevent invalid attention weights.",
     "A padding mask flags [PAD] token positions and sets their attention weights to -infinity before softmax.",
     "It allows variable-length sequences to be processed in parallel within rectangular batch tensors.",
     ["Identify indices containing [PAD] token IDs in batch.", "Construct boolean mask tensor.", "Set attention scores for padded positions to -1e9 before softmax."],
     "Padding masks prevent padding tokens from influencing genuine sequence representations.",
     "Attention Is All You Need", "https://arxiv.org/abs/1706.03762", 2017, "Vaswani et al."),

    (62, 5, "Encoder-Only (BERT)", "encoder-only-bert", "Beginner",
     "Bidirectional transformer encoder reading full context for classification and embedding.",
     "Encoder-only architectures like BERT process tokens with full bidirectional self-attention, allowing every token to attend to both left and right context.",
     "They excel at sentence classification, named entity recognition, and dense embedding extraction.",
     ["Feed sequence with [CLS] token at position 0.", "Pass through stacked bidirectional transformer encoder blocks.", "Extract [CLS] hidden vector for classification tasks."],
     "Encoder-only models provide rich bidirectional representations for comprehension and classification tasks.",
     "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding", "https://arxiv.org/abs/1810.04805", 2018, "Devlin et al."),

    (63, 5, "Decoder-Only (GPT)", "decoder-only-gpt", "Beginner",
     "Causal transformer architecture trained to predict the next token autoregressively.",
     "Decoder-only architectures like GPT apply causal attention masks at every layer, enabling token-by-token text generation.",
     "They form the dominant architecture for generative large language models.",
     ["Feed prompt tokens through stacked causal transformer layers.", "Compute next-token probability distribution from final token representation.", "Append sampled token and repeat."],
     "Decoder-only models unify comprehension and generative reasoning into next-token prediction.",
     "Language Models are Unsupervised Multitask Learners", "https://cdn.openai.com/better-language-models/language_models_are_unsupervised_multitask_learners.pdf", 2019, "Radford et al."),

    (64, 5, "Encoder-Decoder (T5)", "encoder-decoder-t5", "Intermediate",
     "Bidirectional encoder coupled with causal autoregressive decoder via cross-attention.",
     "Encoder-Decoder models like T5 process input sequences bidirectionally with an encoder, while a decoder generates output tokens autoregressively using cross-attention.",
     "They provide strong performance for sequence-to-sequence tasks like translation and summarization.",
     ["Encoder processes full input bidirectionally, generating context representations.", "Decoder generates output tokens causally.", "Decoder layers perform cross-attention over all encoder representations."],
     "Encoder-Decoder architectures cleanly separate source comprehension from target generation.",
     "Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer", "https://arxiv.org/abs/1910.10683", 2019, "Raffel et al."),

    (65, 5, "Cross-Attention", "cross-attention", "Intermediate",
     "Mechanism where decoder queries attend over encoder key and value representations.",
     "In cross-attention, Query vectors come from the preceding decoder layer, while Key and Value vectors come from the encoder's output representations.",
     "It allows decoders to focus on relevant sections of the input text during generation.",
     ["Compute Query matrix Q from decoder hidden states.", "Use encoder output as Key matrix K and Value matrix V.", "Compute Attention(Q_dec, K_enc, V_enc) to extract relevant input context."],
     "Cross-attention connects decoder generation steps directly to encoder source context.",
     "Attention Is All You Need", "https://arxiv.org/abs/1706.03762", 2017, "Vaswani et al.")
]

print(f"Loaded {len(concepts)} concepts so far.")
