part2_concepts = [
    # 6. Training LLMs (66-81)
    (66, 6, "Pre-training Objective (CLM)", "clm", "Beginner",
     "Causal Language Modeling: optimizing likelihood of the next token given all preceding tokens.",
     "Causal Language Modeling trains the model to maximize the log likelihood sum(log P(w_t | w_1, ..., w_{t-1})) across massive unannotated corpora.",
     "It allows self-supervised learning without expensive manual data labeling.",
     ["Pass text sequence into causal transformer.", "Calculate cross-entropy loss between output logits and next token ID at every position.", "Update weights using gradient backpropagation."],
     "CLM turns raw unannotated text into continuous self-supervised training signal.",
     "Improving Language Understanding by Generative Pre-Training", "https://openai.com/research/language-unsupervised", 2018, "Radford et al."),

    (67, 6, "Pre-training Objective (MLM)", "mlm", "Beginner",
     "Masked Language Modeling: predicting randomly masked tokens from bidirectional context.",
     "Masked Language Modeling (BERT-style) masks 15% of input tokens and trains the model to reconstruct the original tokens using bidirectional context.",
     "It teaches deep bidirectional context representations for comprehension tasks.",
     ["Replace 15% of tokens with [MASK], random tokens, or unchanged tokens.", "Pass sequence through bidirectional transformer.", "Compute cross-entropy loss specifically on the masked token positions."],
     "MLM trains bidirectional comprehension by filling in intentionally corrupted text spans.",
     "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding", "https://arxiv.org/abs/1810.04805", 2018, "Devlin et al."),

    (68, 6, "Training Data Pipeline", "training-data-pipeline", "Intermediate",
     "End-to-end data processing: web crawl, heuristic filtering, deduplication, and quality scoring.",
     "The data preparation pipeline transforms raw web crawls into clean training corpora via URL filtering, text extraction, exact/fuzzy deduplication (MinHash), toxicity filtering, and quality classifiers.",
     "Data quality and diversity are the primary determinants of downstream model performance and factual accuracy.",
     ["Download raw web snapshots (e.g. Common Crawl).", "Filter non-target languages, HTML boilerplate, and adult content.", "Run MinHash/LSH deduplication to remove duplicate pages.", "Apply quality classification scoring before tokenization."],
     "High data curation standards dramatically outperform raw web volume for LLM capabilities.",
     "The RefinedWeb Dataset for Falcon LLM", "https://arxiv.org/abs/2306.01116", 2023, "Penedo et al."),

    (69, 6, "Data Contamination", "data-contamination", "Intermediate",
     "Inadvertent leakage of evaluation benchmark questions and answers into training corpora.",
     "Data contamination occurs when test questions or validation datasets appear in pre-training corpora, inflating reported benchmark scores.",
     "Detecting and filtering contaminated samples is essential for honest capability evaluation.",
     ["Search pre-training datasets for n-gram overlaps with popular benchmarks (MMLU, GSM8K).", "Analyze exact match vs paraphrased question leakage.", "Measure performance discrepancies on clean vs leaked benchmark subsets."],
     "Benchmark decontamination ensures evaluation scores reflect true generalization rather than memorization.",
     "A Survey on Data Contamination in Large Language Models", "https://arxiv.org/abs/2310.17589", 2023, "Deng et al."),

    (70, 6, "Batch Size & Gradient Accumulation", "batch-size-gradient-accumulation", "Intermediate",
     "Simulating massive effective batch sizes across limited GPU memory by accumulating gradients.",
     "Gradient accumulation executes multiple forward and backward passes with smaller micro-batches, summing the resulting gradients before performing a single optimizer step.",
     "It allows practitioners to achieve optimal large batch training dynamics on hardware with constrained VRAM.",
     ["Execute forward pass on micro-batch.", "Compute loss and backpropagate gradients without zeroing optimizer state.", "Repeat across N micro-batches.", "Execute optimizer step and zero accumulated gradients."],
     "Gradient accumulation decouples mathematical batch size from physical GPU VRAM limits.",
     "Accurate, Large Minibatch SGD: Training ImageNet in 1 Hour", "https://arxiv.org/abs/1706.02677", 2017, "Goyal et al."),

    (71, 6, "Learning Rate Scheduling", "learning-rate-scheduling", "Intermediate",
     "Dynamic learning rate adjustment with linear warmup and cosine decay.",
     "A learning rate schedule ramps up the rate linearly from zero over initial steps (warmup) and decays it following a cosine curve toward a minimum floor.",
     "Warmup stabilizes early gradients when weight variance is high, while cosine decay allows fine-grained convergence.",
     ["Linear warmup: increase lr from 0 to lr_max over first w steps.", "Cosine decay: scale lr according to 0.5 * (1 + cos(pi * step / max_steps)).", "Apply scheduled rate to optimizer updates."],
     "Cosine decay with linear warmup produces the most reliable convergence for LLM pre-training.",
     "SGDR: Stochastic Gradient Descent with Warm Restarts", "https://arxiv.org/abs/1608.03983", 2016, "Loshchilov, Hutter"),

    (72, 6, "Mixed Precision Training", "mixed-precision-training", "Advanced",
     "Accelerating training and halving memory using FP16/BF16 arithmetic with FP32 master weights.",
     "Mixed precision performs forward passes and activation storage in 16-bit floating point (BF16 or FP16) while keeping a 32-bit (FP32) copy of master weights for optimizer updates.",
     "It doubles compute throughput on Tensor Cores and cuts activation memory by 50%.",
     ["Cast weights and activations to 16-bit float (BF16 or FP16).", "Compute forward pass and loss.", "Apply dynamic loss scaling if using FP16 to prevent underflow.", "Backpropagate and update FP32 master weights."],
     "BF16 mixed precision provides wide dynamic range, eliminating manual loss scaling during pre-training.",
     "Mixed Precision Training", "https://arxiv.org/abs/1710.03740", 2017, "Micikevicius et al."),

    (73, 6, "Training Loss Curves", "training-loss-curves", "Beginner",
     "Empirical trajectory of cross-entropy loss across tokens and training compute.",
     "Training loss curves plot cross-entropy loss against training steps or token counts on a log-log scale.",
     "They indicate learning health, learning rate stability, and smooth convergence toward loss floors.",
     ["Record cross-entropy loss at periodic step intervals.", "Plot loss on log scale against accumulated tokens.", "Monitor for loss spikes, plateaus, or divergence."],
     "Smooth power-law loss descent confirms healthy optimization and predictable scaling.",
     "Scaling Laws for Neural Language Models", "https://arxiv.org/abs/2001.08361", 2020, "Kaplan et al."),

    (74, 6, "Scaling Laws", "scaling-laws", "Intermediate",
     "Empirical power laws connecting compute, parameter count, dataset size, and loss (Chinchilla).",
     "Chinchilla scaling laws prove that for compute-optimal training, parameter count and dataset token count should be scaled in equal proportion (1:1).",
     "It prevents over-allocating compute to oversized models trained on insufficient tokens.",
     ["Express compute budget: C approx 6 * N * D FLOPs.", "Derive optimal parameter count: N_opt proportional to C^0.5.", "Derive optimal training tokens: D_opt proportional to C^0.5."],
     "Compute-optimal training scales parameters and token counts equally.",
     "Training Compute-Optimal Large Language Models", "https://arxiv.org/abs/2203.15556", 2022, "Hoffmann et al. (Chinchilla)"),

    (75, 6, "Data Parallelism", "data-parallelism", "Intermediate",
     "Replicating the entire model across multiple GPUs and distributing distinct batch slices.",
     "Data Parallelism places identical model copies on N GPUs, feeds each a unique slice of the mini-batch, and averages gradients via All-Reduce before parameter updates.",
     "It is the simplest and most widely used multi-GPU scaling strategy.",
     ["Broadcast identical model weights to all GPUs.", "Compute forward and backward passes on local data shards.", "Execute All-Reduce communication to average gradients across all GPUs.", "Update local model weights synchronously."],
     "Data parallelism scales throughput linearly when model parameters fit comfortably in a single GPU.",
     "PyTorch Distributed: Experiences on Accelerating Data Parallel Training", "https://arxiv.org/abs/2006.15704", 2020, "Li et al."),

    (76, 6, "Model Parallelism (Tensor)", "model-parallelism-tensor", "Advanced",
     "Splitting individual weight matrices across GPUs along rows or columns (Megatron-LM).",
     "Tensor Parallelism partitions weight matrices across GPUs (e.g. column-parallel in first FFN layer, row-parallel in second), synchronizing activations via All-Reduce.",
     "It allows training individual layers too large to fit in the VRAM of a single GPU.",
     ["Split linear weight matrix W into N column shards across N GPUs.", "Multiply input X by local shard W_i on each GPU in parallel.", "Apply All-Reduce or All-Gather across high-speed NVLink interconnect."],
     "Tensor parallelism partitions individual matrix multiplications across GPUs over high-bandwidth links.",
     "Megatron-LM: Training Multi-Billion Parameter Language Models Using Model Parallelism", "https://arxiv.org/abs/1909.08053", 2019, "Shoeybi et al."),

    (77, 6, "Pipeline Parallelism", "pipeline-parallelism", "Advanced",
     "Partitioning consecutive transformer layers across GPUs with microbatch pipelining.",
     "Pipeline Parallelism assigns sequential subsets of model layers to different GPUs in a daisy chain, dividing mini-batches into micro-batches to minimize idle bubble time.",
     "It enables training giant models across nodes connected by standard networking.",
     ["Assign layers 1-8 to GPU 0, 9-16 to GPU 1, and so on.", "Split mini-batch into M micro-batches.", "Pipe forward activations down the chain and backward gradients back up the chain."],
     "Pipeline schedules like 1F1B minimize idle bubble overhead across sequential GPU stages.",
     "GPipe: Efficient Training of Giant Neural Networks using Pipeline Parallelism", "https://arxiv.org/abs/1811.06965", 2018, "Huang et al."),

    (78, 6, "ZeRO (Zero Redundancy Optimizer)", "zero", "Advanced",
     "Partitioning optimizer states, gradients, and model parameters across data-parallel ranks.",
     "ZeRO eliminates memory redundancies in data parallelism across three stages: ZeRO-1 (partitions optimizer states), ZeRO-2 (partitions gradients), and ZeRO-3 (partitions parameters).",
     "It achieves memory savings proportional to GPU count without the complexity of tensor parallelism.",
     ["ZeRO-1: Each GPU stores 1/N of FP32 optimizer states (4x memory reduction).", "ZeRO-2: Each GPU stores 1/N of gradients (8x memory reduction).", "ZeRO-3: Each GPU stores 1/N of parameters, gathering weights just-in-time for forward/backward passes."],
     "ZeRO-3 allows training trillion-parameter models by sharding all training states across the cluster.",
     "ZeRO: Memory Optimizations Toward Training Trillion Parameter Models", "https://arxiv.org/abs/1910.02054", 2019, "Rajbhandari et al."),

    (79, 6, "Gradient Checkpointing", "gradient-checkpointing", "Advanced",
     "Trading compute for memory by discarding forward activations and recomputing during backpropagation.",
     "Gradient checkpointing saves activation tensors at a few select layer boundaries and recomputes intermediate activations on the fly during the backward pass.",
     "It slashes activation memory from O(N) to O(sqrt(N)) at the cost of approximately 20-30% extra forward compute.",
     ["Run forward pass, caching activations only at specified checkpoint layers.", "During backward pass, re-run local forward pass between checkpoints to generate needed activations.", "Compute gradients and free memory immediately."],
     "Gradient checkpointing enables training significantly larger models or batch sizes on existing VRAM.",
     "Training Deep Nets with Sublinear Memory Cost", "https://arxiv.org/abs/1604.06174", 2016, "Chen et al."),

    (80, 6, "Tokenizer Training", "tokenizer-training", "Intermediate",
     "Training a subword tokenizer from raw text corpora using pair frequency statistics.",
     "Tokenizer training scans large corpus samples to count character and substring frequencies, iteratively building a merge table up to the specified vocabulary size.",
     "A well-trained tokenizer maximizes compression and preserves morphological word units.",
     ["Tokenize training corpus into unicode characters.", "Iterate: find most frequent adjacent symbol pair.", "Merge pair into single vocabulary token and update corpus frequencies.", "Stop when vocabulary size reaches target (e.g. 32K or 128K)."],
     "Tokenizer training is an unsupervised pre-processing stage that fixes the discrete alphabet of the model.",
     "Byte Pair Encoding Tokenization", "https://huggingface.co/docs/transformers/tokenizer_summary", 2021, "Hugging Face"),

    (81, 6, "Curriculum Learning", "curriculum-learning", "Intermediate",
     "Structuring training data progression from simple concepts to complex sequences.",
     "Curriculum learning exposes models to shorter, cleaner, simpler textual examples early in training before introducing complex, multi-lingual, and technical documents.",
     "It speeds up early optimization and guides parameters toward smoother basins of attraction.",
     ["Score training examples by complexity (length, vocabulary rarity, syntactic depth).", "Order dataset to present simple samples during early epochs.", "Gradually increase difficulty threshold as loss decreases."],
     "Presenting structured data difficulty curves accelerates early convergence in deep learning.",
     "Curriculum Learning", "https://dl.acm.org/doi/10.1145/1553374.1553380", 2009, "Bengio et al."),

    # 7. Text Generation & Decoding (82-95)
    (82, 7, "Autoregressive Generation", "autoregressive", "Beginner",
     "Iterative generation loop predicting one token at a time and appending it to the context.",
     "Autoregressive generation predicts the probability distribution over the vocabulary for position t+1, samples a token, appends it to the sequence, and feeds the extended sequence back into the model.",
     "It is the fundamental loop powering conversational AI and text completion.",
     ["Pass current token sequence into causal transformer.", "Extract output logits from the final token position.", "Sample next token from probability distribution.", "Append new token to prompt and repeat until stop token."],
     "Autoregressive generation transforms next-token prediction into coherent long-form text generation.",
     "Language Models are Unsupervised Multitask Learners", "https://cdn.openai.com/better-language-models/language_models_are_unsupervised_multitask_learners.pdf", 2019, "Radford et al."),

    (83, 7, "Logits & Softmax (Generation)", "logits-softmax-generation", "Beginner",
     "Converting raw unnormalized model score vectors into next-token probability distributions.",
     "The final linear unembedding layer projects hidden states to a vector of raw scores (logits) of length |V|, which softmax converts to candidate probabilities.",
     "Logits define the relative preference of the model before temperature and sampling filters are applied.",
     ["Multiply final hidden state h_T by unembedding matrix W_u.", "Obtain raw logit vector z of size |V|.", "Apply softmax: p_i = exp(z_i) / sum(exp(z_j))."],
     "Unembedding logits represent the raw unnormalized preferences over the entire vocabulary.",
     "Deep Learning", "https://www.deeplearningbook.org/", 2016, "Goodfellow, Bengio, Courville"),

    (84, 7, "Greedy Decoding", "greedy-decoding", "Beginner",
     "Deterministically selecting the single token with the highest predicted probability at each step.",
     "Greedy decoding picks argmax P(w_t | w_<t) at every generation step without any stochastic sampling.",
     "It is computationally fast and deterministic, but frequently causes repetitive loops and misses globally high-scoring sequences.",
     ["Compute softmax probabilities over vocabulary.", "Select index with maximum probability: t_next = argmax(p).", "Append selected token to context."],
     "Greedy decoding is deterministic but vulnerable to repetitive generation loops.",
     "Speech and Language Processing", "https://web.stanford.edu/~jurafsky/slp3/", 2024, "Jurafsky, Martin"),

    (85, 7, "Beam Search", "beam-search", "Intermediate",
     "Heuristic search maintaining top-B candidate sequences in parallel to maximize cumulative probability.",
     "Beam search maintains a fixed number B (beam width) of highest-scoring partial sequences at each step, expanding all candidates and pruning back to the top B.",
     "It discovers higher cumulative probability outputs than greedy decoding for structured translation and summarization.",
     ["Initialize beam with prompt.", "At each step, expand all B sequences across vocabulary candidates.", "Score sequences by cumulative log probability: sum(log P(w_i)).", "Prune to top B candidates and repeat."],
     "Beam search explores multiple hypotheses in parallel to avoid locally suboptimal choices.",
     "Speech and Language Processing", "https://web.stanford.edu/~jurafsky/slp3/", 2024, "Jurafsky, Martin"),

    (86, 7, "Temperature", "temperature", "Beginner",
     "Hyperparameter scaling logit sharpness: z / T before applying softmax.",
     "Temperature divides logits by scalar T before softmax: p_i = exp(z_i / T) / sum(exp(z_j / T)). T < 1 sharpens probabilities toward greedy selection; T > 1 flattens probabilities toward uniform randomness.",
     "It provides direct control over generation creativity and randomness.",
     ["Divide all unnormalized logits by temperature scalar T.", "Apply softmax to scaled logits.", "Sample from the resulting sharpened or flattened probability distribution."],
     "Lower temperature focuses on high-confidence tokens; higher temperature encourages diversity.",
     "The Curious Case of Neural Text Deferral and Sampling", "https://arxiv.org/abs/1904.09751", 2019, "Holtzman et al."),

    (87, 7, "Top-k Sampling", "top-k-sampling", "Beginner",
     "Restricting sampling to the K most probable tokens and renormalizing their probabilities.",
     "Top-k sampling sorts candidate tokens by probability, zeros out all candidates outside the top K, and renormalizes the remaining distribution.",
     "It prevents the model from sampling low-probability, nonsensical tokens from the long tail of the vocabulary.",
     ["Sort vocabulary logits in descending order.", "Keep only top K entries, setting all other logits to -infinity.", "Renormalize with softmax and sample."],
     "Top-k eliminates the tail of low-quality tokens while preserving local diversity.",
     "Hierarchical Neural Story Generation", "https://arxiv.org/abs/1805.04833", 2018, "Fan, Lewis, Dauphin"),

    (88, 7, "Top-p (Nucleus) Sampling", "top-p-sampling", "Intermediate",
     "Dynamically selecting the smallest set of tokens whose cumulative probability exceeds P.",
     "Top-p (Nucleus) sampling dynamically adjusts candidate pool size by including only tokens from the top of the sorted distribution until their cumulative sum reaches threshold P (e.g. 0.9).",
     "It expands candidate count when confidence is low and narrows it to one or two tokens when confidence is high.",
     ["Sort tokens by probability descending.", "Compute cumulative probability sum.", "Discard all tokens following the point where cumulative sum exceeds P.", "Renormalize remaining nucleus and sample."],
     "Nucleus sampling dynamically adapts candidate pool size based on model prediction confidence.",
     "The Curious Case of Neural Text Degeneration", "https://arxiv.org/abs/1904.09751", 2019, "Holtzman et al."),

    (89, 7, "Min-p Sampling", "min-p-sampling", "Intermediate",
     "Filtering tokens whose probability is below a threshold relative to the top candidate.",
     "Min-p filters out any token whose probability is less than min_p * p_max, scaling the cutoff dynamically relative to the highest probability candidate.",
     "It provides a robust alternative to top-p that handles both flat and peaked distributions cleanly.",
     ["Identify highest token probability p_max.", "Calculate dynamic cutoff threshold: threshold = min_p * p_max.", "Zero out all tokens with probability below threshold and renormalize."],
     "Min-p scales token cutoff relative to the top prediction, maintaining natural vocabulary diversity.",
     "Min-p Sampling for Large Language Models", "https://github.com/oobabooga/text-generation-webui/pull/4000", 2023, "Menendez et al."),

    (90, 7, "Repetition Penalty", "repetition-penalty", "Beginner",
     "Discounting logits of previously generated tokens to prevent repetitive loops.",
     "Repetition penalty divides positive logits by scalar theta (or multiplies negative logits by theta) for all tokens that have already appeared in the context.",
     "It breaks deterministic repetition loops in greedy and low-temperature decoding.",
     ["Check context for previously emitted token IDs.", "For each previously generated token, scale logit: z_i = z_i / theta if z_i > 0 else z_i * theta.", "Compute softmax on modified logits."],
     "Repetition penalties discourage models from looping on phrases they have already output.",
     "CTRL: A Conditional Transformer Language Model for Controllable Generation", "https://arxiv.org/abs/1909.05858", 2019, "Keskar et al."),

    (91, 7, "Frequency & Presence Penalty", "frequency-presence-penalty", "Intermediate",
     "Penalizing tokens based on exact occurrence count (frequency) or single appearance (presence).",
     "Frequency penalty subtracts a constant times token count from logits (penalizing repeated use); Presence penalty subtracts a flat constant if the token appeared at least once (encouraging new topics).",
     "They provide granular control over vocabulary diversity and topic switching in API generation.",
     ["Count occurrences count(t) of each token in generated output.", "Apply penalty: logit(t) = logit(t) - (frequency_penalty * count(t) + presence_penalty * (count(t) > 0)).", "Apply softmax and sample."],
     "Frequency penalty reduces word repetition; presence penalty promotes introduction of new concepts.",
     "OpenAI API Documentation", "https://platform.openai.com/docs/guides/text-generation", 2023, "OpenAI"),

    (92, 7, "Stop Sequences", "stop-sequences", "Beginner",
     "Strings and special tokens triggering immediate termination of the generation loop.",
     "A stop sequence is a specified string or token ID (e.g. <|endoftext|>, 'User:', '\n\n') that halts autoregressive decoding immediately when matched in output text.",
     "It enforces turn-taking in chatbots and formats structured outputs cleanly.",
     ["After sampling new token, append to running text buffer.", "Check if buffer ends with any configured stop sequence string.", "Halt generation loop immediately upon match and strip stop string."],
     "Stop sequences provide clean control boundaries for conversational and tool-augmented generation.",
     "Speech and Language Processing", "https://web.stanford.edu/~jurafsky/slp3/", 2024, "Jurafsky, Martin"),

    (93, 7, "Structured Output (JSON Mode)", "structured-output-json", "Intermediate",
     "Constrained decoding using finite state machines or grammars to guarantee valid JSON syntax.",
     "Structured output uses a parser or context-free grammar during decoding to mask out any tokens that would violate the specified schema or JSON syntax rules at each step.",
     "It guarantees 100% syntactically valid JSON responses without parsing errors.",
     ["Parse schema into an active grammar state machine.", "At step t, identify which vocabulary tokens produce valid syntactic transitions.", "Set logits for all invalid tokens to -infinity.", "Sample strictly from grammatically valid candidate tokens."],
     "Grammar-constrained decoding guarantees syntax validity directly at the token generation level.",
     "Grammar-Aligned Decoding for Large Language Models", "https://arxiv.org/abs/2402.05099", 2024, "Willard, Louf (Outlines)"),

    (94, 7, "Speculative Decoding", "speculative-decoding", "Advanced",
     "Accelerating generation using a small draft model verified in parallel by the target model.",
     "A lightweight draft model rapidly generates K candidate tokens autoregressively, and the large target model evaluates all K tokens in a single parallel forward pass, accepting matching prefixes.",
     "It speeds up inference 2-3x with mathematically identical output distributions.",
     ["Draft model generates K candidate tokens quickly.", "Target model runs a single forward pass over all K tokens simultaneously.", "Accept first M matching tokens and resample the first mismatch from adjusted distribution."],
     "Speculative decoding converts slow autoregressive decoding into parallel verification.",
     "Fast Inference from Transformers via Speculative Decoding", "https://arxiv.org/abs/2211.17192", 2022, "Leviathan, Kalman, Matias"),

    (95, 7, "Sampling Strategy Comparison", "sampling-comparison", "Beginner",
     "Side-by-side behavioral comparison of greedy, beam search, temperature, top-k, and nucleus sampling.",
     "Comparing decoding strategies on identical prompts reveals the tradeoffs between determinism, diversity, creativity, and repetition across sampling algorithms.",
     "Understanding these differences enables practitioners to select optimal decoding parameters per task.",
     ["Execute generation with identical seed across 6 distinct decoding strategies.", "Compare output creativity, coherence, and lexical diversity side by side.", "Inspect underlying token probability distributions."],
     "Different generation tasks require tailored decoding strategies: greedy for code/math, nucleus for creative prose.",
     "The Curious Case of Neural Text Degeneration", "https://arxiv.org/abs/1904.09751", 2019, "Holtzman et al."),

    # 8. Attention Visualizations (96-103)
    (96, 8, "Self-Attention Heatmap", "self-attention-heatmap", "Beginner",
     "Two-dimensional matrix visualization of pairwise attention weights between all sequence tokens.",
     "A self-attention heatmap displays the N x N attention matrix as a color-coded grid where cell (i, j) indicates how strongly token i attends to token j.",
     "It provides intuitive visual inspection of internal token routing and contextual dependencies.",
     ["Extract attention score matrix A = softmax(Q * K^T / sqrt(d_k)).", "Map attention weights (0.0 to 1.0) to color intensity.", "Render interactive NxN grid with token labels on both axes."],
     "Attention heatmaps reveal which context tokens influence each output representation.",
     "Attention Is All You Need", "https://arxiv.org/abs/1706.03762", 2017, "Vaswani et al."),

    (97, 8, "Cross-Attention Heatmap", "cross-attention-heatmap", "Intermediate",
     "Matrix mapping attention alignment between target decoder tokens and source encoder tokens.",
     "Cross-attention heatmaps display alignment weights of size T_target x T_source, illustrating which source tokens are consulted as each target word is produced.",
     "They visualize translation word alignments and document citation linkages.",
     ["Extract cross-attention weights between decoder queries and encoder keys.", "Render rectangular grid of size Target Tokens x Source Tokens.", "Observe dynamic alignment shifts as translation progresses."],
     "Cross-attention matrices visualize alignment mappings between source and generated target sequences.",
     "Neural Machine Translation by Jointly Learning to Align and Translate", "https://arxiv.org/abs/1409.0473", 2014, "Bahdanau, Cho, Bengio"),

    (98, 8, "Multi-Head Patterns", "multi-head-patterns", "Intermediate",
     "Comparing attention matrices across different heads to reveal specialized learned behaviors.",
     "Inspecting all H heads within a layer demonstrates how distinct heads specialize: some focus on immediately adjacent tokens, others track syntactic verbs, and others capture coreference.",
     "It shows how multi-head attention avoids collapsing into a single representation pattern.",
     ["Extract attention matrices across all heads for a chosen layer.", "Render side-by-side heatmaps for each head.", "Identify positional, delimiter, and grammatical head patterns."],
     "Multi-head attention distributes diverse linguistic tracking tasks across distinct parallel heads.",
     "Analyzing Multi-Head Self-Attention: Specialized Heads Do the Heavy Lifting", "https://arxiv.org/abs/1905.09418", 2019, "Voita et al."),

    (99, 8, "Attention Over Layers", "attention-over-layers", "Intermediate",
     "Evolution of attention patterns from low-level positional syntax in early layers to high-level semantics in deep layers.",
     "In early transformer layers, attention is primarily localized and positional; in middle layers, it tracks syntactic relationships; in deep layers, it becomes diffuse and semantic.",
     "Tracking layers reveals the hierarchical abstraction formed by deep networks.",
     ["Inspect attention matrices layer by layer from layer 1 to layer L.", "Observe transition from sharp diagonal bands to broad semantic attention.", "Quantify attention entropy growth across network depth."],
     "Transformer representations progress from local syntax in early layers to global semantics in deep layers.",
     "What Does BERT Look At? An Analysis of BERT's Attention", "https://arxiv.org/abs/1906.04341", 2019, "Clark et al."),

    (100, 8, "BERTViz-Style Visualizations", "bertviz-style", "Intermediate",
     "Interactive connecting arcs between tokens showing head weights and layer routing.",
     "BERTViz-style visualizations connect tokens on two parallel text lines with colored arcs whose thickness and opacity correspond to attention weight magnitude.",
     "It provides an intuitive interface for exploring multi-head and multi-layer attention dynamics.",
     ["Display token sequence on left and right columns.", "Draw bezier connecting arcs between tokens with stroke width proportional to attention weight.", "Allow interactive filtering by head, layer, and token click."],
     "Interactive attention arcs provide immediate visual understanding of token-to-token connections.",
     "A Multiscale Visualization of Attention in the Transformer Model", "https://arxiv.org/abs/1906.05714", 2019, "Jesse Vig"),

    (101, 8, "Attention Sink", "attention-sink", "Advanced",
     "Phenomenon where initial tokens absorb disproportionate attention mass regardless of semantic relevance.",
     "In autoregressive models with Softmax, the first token (BOS or initial word) absorbs surplus attention scores when no other token is relevant, acting as a numerical 'sink'.",
     "Preserving initial sink tokens is crucial for maintaining stability in streaming and sliding-window generation.",
     ["Measure attention weight distribution across positions in long sequences.", "Observe initial token receiving 30-50% of total attention mass even on unrelated text.", "Retain initial sink tokens in KV cache to prevent perplexity explosion."],
     "Initial tokens serve as numerical sinks for unneeded attention mass in Softmax self-attention.",
     "Efficient Streaming Language Models with Attention Sinks", "https://arxiv.org/abs/2309.17453", 2023, "Xiao et al."),

    (102, 8, "Attention Rollout", "attention-rollout", "Advanced",
     "Matrix multiplication across layers tracking information flow from input tokens to final representations.",
     "Attention Rollout recursively multiplies layer attention matrices combined with residual identity weights: R_l = (0.5 * A_l + 0.5 * I) * R_{l-1}.",
     "It computes the effective total contribution of each input token to final output representations.",
     ["Add identity matrix to each layer attention matrix to account for residual connections.", "Normalize row sums to 1.0.", "Multiply matrices sequentially from layer 1 to layer L to obtain cumulative rollout."],
     "Attention Rollout tracks the compounding flow of information through deep residual layers.",
     "Quantifying Attention Flow in Transformers", "https://arxiv.org/abs/2005.00928", 2020, "Abnar, Zuidema"),

    (103, 8, "Attention vs Linear Attention", "attention-vs-linear", "Advanced",
     "Quadratic O(n^2) standard attention complexity versus linear O(n) kernel approximations.",
     "Standard attention requires computing an N x N matrix with O(n^2) time and memory complexity; Linear attention uses kernel feature maps to compute K^T * V first in O(n * d^2) time.",
     "Linear attention enables processing sequences with millions of tokens on standard hardware.",
     ["Express standard attention: softmax(Q * K^T) * V with O(n^2) cost.", "Express linear attention using kernel map phi: phi(Q) * (phi(K)^T * V) with O(n) cost.", "Compare execution time and memory across sequence lengths up to 100K tokens."],
     "Linear attention avoids quadratic matrix explosion by reordering associative matrix multiplications.",
     "Transformers are RNNs: Fast Autoregressive Transformers with Linear Attention", "https://arxiv.org/abs/2006.16236", 2020, "Katharopoulos et al."),

    # 9. Context & Memory (104-113)
    (104, 9, "Context Window", "context-window", "Beginner",
     "Maximum number of tokens an LLM can process in a single forward pass without truncation.",
     "The context window defines the maximum sequence length (input prompt + generated output) that a model's positional encodings and memory capacity support.",
     "Larger context windows enable analysis of full books, codebases, and extensive chat histories.",
     ["Count input tokens using tokenizer.", "Compare total tokens against model context limits (e.g. 4K, 8K, 32K, 128K, 1M+).", "Determine available token budget for generation."],
     "Context window limits govern how much reference information a model can consult simultaneously.",
     "Language Models are Few-Shot Learners", "https://arxiv.org/abs/2005.14165", 2020, "Brown et al."),

    (105, 9, "KV Cache", "kv-cache", "Intermediate",
     "Caching Key and Value tensors of past tokens to avoid redundant recomputation during generation.",
     "During autoregressive generation, past tokens do not change. By caching their computed Key and Value vectors in GPU memory, step t only requires computing Q, K, V for the single new token.",
     "It transforms generation step complexity from O(t^2) compute to O(t) memory retrieval.",
     ["Compute and store K and V vectors for all prompt tokens in cache buffer.", "For new token t, compute only q_t, k_t, v_t.", "Append k_t and v_t to KV cache.", "Compute attention of q_t against all cached Keys and Values."],
     "KV caching trades GPU VRAM for massive generation speedups during autoregressive decoding.",
     "Efficient Memory Management for Large Language Model Serving with PagedAttention", "https://arxiv.org/abs/2309.06180", 2023, "Kwon et al. (vLLM)"),

    (106, 9, "KV Cache Memory Calculator", "kv-cache-memory", "Intermediate",
     "Calculating exact VRAM consumption: 2 * 2 * n_layers * n_heads * d_head * seq_len bytes per user.",
     "KV cache memory scales linearly with sequence length: Memory = 2 (K and V) * bytes_per_elem * n_layers * n_heads * d_head * seq_len * batch_size.",
     "KV cache often consumes more GPU memory than model weights during high-concurrency serving.",
     ["Determine precision (e.g. 2 bytes for FP16/BF16).", "Multiply 2 * precision * num_layers * num_kv_heads * head_dim * context_length.", "Calculate total gigabytes per concurrent request."],
     "KV cache VRAM requirements frequently bottleneck concurrent inference throughput.",
     "Efficient Memory Management for Large Language Model Serving with PagedAttention", "https://arxiv.org/abs/2309.06180", 2023, "Kwon et al. (vLLM)"),

    (107, 9, "Sliding Window Attention", "sliding-window-attention", "Intermediate",
     "Restricting token attention to a local fixed-size window W of preceding tokens (Mistral).",
     "Sliding Window Attention restricts each token to attending only to the W previous tokens, capping the KV cache size at W while allowing information to propagate W * L layers deep.",
     "It maintains bounded memory consumption over arbitrarily long sequence generation.",
     ["Define window size W (e.g. 4096 tokens).", "Construct attention mask allowing attention only to indices [i - W, i].", "Recycle KV cache slots using circular ring buffers."],
     "Sliding window attention caps memory consumption while multi-layer depth provides wide receptive fields.",
     "Mistral 7B", "https://arxiv.org/abs/2310.06825", 2023, "Jiang et al."),

    (108, 9, "Sparse Attention", "sparse-attention", "Advanced",
     "Structured attention masks combining local window, strided steps, and global anchor tokens.",
     "Sparse attention constructs sparse connectivity graphs (combining local neighbors, strided hops, and global tokens like [CLS]), reducing attention complexity to O(n * sqrt(n)).",
     "It enables scaling context windows to tens of thousands of tokens before Flash Attention.",
     ["Define local window for nearby tokens.", "Define strided pattern (every s-th token) for periodic sampling.", "Define global tokens that attend to all positions and are attended to by all positions."],
     "Sparse attention patterns reduce attention computation while preserving long-range routing paths.",
     "Generating Long Sequences with Sparse Transformers", "https://arxiv.org/abs/1904.10509", 2019, "Child et al."),

    (109, 9, "Flash Attention", "flash-attention", "Advanced",
     "IO-aware exact attention algorithm computing softmax and matmul in fast GPU SRAM using tiling.",
     "Flash Attention tiles Query, Key, and Value matrices into small blocks that fit in fast on-chip SRAM, computing online softmax without materializing the huge N x N attention matrix in slow HBM.",
     "It provides 2-4x speedups and reduces memory footprint from quadratic O(N^2) to linear O(N) with exact numerical precision.",
     ["Load block of Q into SRAM.", "Iterate over blocks of K and V from high-bandwidth memory (HBM) into SRAM.", "Compute online softmax scaling factor dynamically.", "Accumulate partial output representations and write final result back to HBM."],
     "Flash Attention eliminates memory IO bottlenecks by computing attention in fast SRAM tiles.",
     "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness", "https://arxiv.org/abs/2205.14135", 2022, "Tri Dao et al."),

    (110, 9, "Ring Attention", "ring-attention", "Advanced",
     "Distributed attention passing Key and Value blocks in a ring across GPUs to handle millions of tokens.",
     "Ring Attention partitions sequence tokens across a ring of N devices; while each GPU computes attention on its local query block, Key and Value blocks are passed asynchronously around the ring.",
     "It enables scaling context length linearly with device count up to millions of tokens without memory bottlenecks.",
     ["Assign sequence chunk i to GPU i.", "GPU i computes attention for local Q_i against local K_i, V_i.", "Pass K_i, V_i to next GPU in ring while receiving K_{i-1}, V_{i-1}.", "Overlap peer-to-peer communication with tensor core computation."],
     "Ring Attention overlaps communication and computation to scale context windows across GPU clusters.",
     "RingAttention with Blockwise Transformers for Near-Infinite Context", "https://arxiv.org/abs/2310.01889", 2023, "Liu et al."),

    (111, 9, "Grouped Query Attention (GQA)", "gqa", "Advanced",
     "Grouping multiple query heads to share a single key-value head pair (LLaMA 2/3).",
     "Grouped Query Attention partitions H query heads into G groups, where all heads in a group share a single Key and Value head.",
     "It slashes KV cache memory by factor H/G while preserving multi-head representation quality.",
     ["Define G query groups (e.g. 8 groups of 4 heads for 32 query heads).", "Project single Key and Value head per group.", "Broadcast shared Key and Value across the 4 Query heads during attention."],
     "GQA achieves high throughput and low memory footprint with near-identical MHA accuracy.",
     "GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints", "https://arxiv.org/abs/2305.13245", 2023, "Ainslie et al."),

    (112, 9, "Multi-Query Attention (MQA)", "mqa", "Advanced",
     "Extreme attention parameter sharing where all query heads share exactly one Key and Value head.",
     "Multi-Query Attention uses distinct Query projections for each head, but shares a single universal Key head and Value head across the entire layer.",
     "It reduces KV cache memory consumption by a factor equal to the number of heads (e.g. 32x or 64x).",
     ["Project H distinct Query heads from hidden state.", "Project exactly 1 Key head and 1 Value head.", "Compute attention for each Query head against the shared Key and Value representations."],
     "MQA minimizes KV cache memory, maximizing concurrent batch throughput on memory-bound inference.",
     "Fast Transformer Decoding: One Write-Head is All You Need", "https://arxiv.org/abs/1911.02150", 2019, "Noam Shazeer"),

    (113, 9, "Context Window Extension (YaRN & RoPE Scaling)", "context-window-extension", "Advanced",
     "Techniques interpolating positional frequencies to extend context length from 4K to 128K+ tokens.",
     "Positional interpolation and YaRN (Yet another RoPE extensioN) scale RoPE rotary frequencies, interpolating position IDs within the original frequency spectrum to prevent out-of-distribution attention failures.",
     "They extend pre-trained models to 32x longer context windows with minimal fine-tuning compute.",
     ["Calculate scaling factor s = L_target / L_original.", "Interpolate high frequencies and extrapolate low frequencies with wavelength-dependent scaling (YaRN).", "Fine-tune model on small high-context dataset."],
     "YaRN and RoPE scaling adapt pre-trained rotary coordinates to long contexts without retraining.",
     "YaRN: Efficient Context Window Extension of Large Language Models", "https://arxiv.org/abs/2309.00071", 2023, "Peng et al."),

    # 10. Alignment & Safety (114-125)
    (114, 10, "Supervised Fine-Tuning (SFT)", "sft", "Beginner",
     "Fine-tuning pre-trained base models on prompt-response instruction datasets.",
     "Supervised Fine-Tuning trains a raw language model on high-quality curated prompt-response pairs using standard cross-entropy loss on the assistant response tokens.",
     "It converts an autocomplete predictor into an interactive assistant that follows instructions.",
     ["Collect dataset of prompt-completion pairs.", "Mask loss on prompt tokens, computing cross-entropy strictly on completion tokens.", "Fine-tune model weights for 2-3 epochs with low learning rate."],
     "SFT teaches pre-trained models the conversational tone and structure expected by users.",
     "Training language models to follow instructions with human feedback", "https://arxiv.org/abs/2203.02155", 2022, "Ouyang et al. (InstructGPT)"),

    (115, 10, "RLHF Pipeline", "rlhf-pipeline", "Intermediate",
     "Three-stage alignment: SFT, Reward Model training on human rankings, and PPO policy optimization.",
     "Reinforcement Learning from Human Feedback (RLHF) aligns models with human preferences via three steps: SFT base tuning, training a scalar reward model on pairwise rankings, and optimizing the policy with PPO.",
     "It significantly improves helpfulness, harmlessness, and honesty beyond pure supervised imitation.",
     ["Train SFT model on demonstration dialogues.", "Generate paired responses (A, B) and collect human preference rankings.", "Train Reward Model to score preferred responses higher.", "Fine-tune SFT policy using PPO to maximize reward while penalizing KL divergence."],
     "RLHF aligns language model behaviors with nuanced human preferences and safety guidelines.",
     "Training language models to follow instructions with human feedback", "https://arxiv.org/abs/2203.02155", 2022, "Ouyang et al. (InstructGPT)"),

    (116, 10, "Reward Modeling", "reward-modeling", "Intermediate",
     "Training a neural model to score response quality based on human pairwise preferences.",
     "A Reward Model replaces the unembedding head with a scalar regression head, trained with binary cross-entropy loss: -log sigma(r(y_w) - r(y_l)) where y_w is the human-preferred response.",
     "It serves as an automated surrogate judge of output quality during reinforcement learning.",
     ["Sample pair of responses (y_w, y_l) for prompt x where human preferred y_w.", "Pass prompt + response through Reward Model to compute scalar scores r(x, y_w) and r(x, y_l).", "Optimize loss: L = -log(sigmoid(r_w - r_l))."],
     "Reward models provide scalar objective signals quantifying subjective response quality.",
     "Learning to summarize from human feedback", "https://arxiv.org/abs/2009.01325", 2020, "Stiennon et al."),

    (117, 10, "PPO (Proximal Policy Optimization)", "ppo", "Advanced",
     "Reinforcement learning algorithm optimizing LLM policies within clipped probability ratios.",
     "PPO optimizes the language model policy to maximize reward model scores while constraining the probability ratio r_t(theta) within a clipped range [1 - eps, 1 + eps] and adding a KL penalty against the original SFT model.",
     "It prevents policy collapse and degeneration during reinforcement learning.",
     ["Generate completions with active policy model.", "Score completions with Reward Model and compute KL divergence penalty against reference SFT model.", "Compute generalized advantage estimates (GAE).", "Update policy parameters using clipped objective."],
     "PPO stabilizes policy updates during RL training, preventing model drift from natural language distributions.",
     "Proximal Policy Optimization Algorithms", "https://arxiv.org/abs/1707.06347", 2017, "Schulman et al."),

    (118, 10, "DPO (Direct Preference Optimization)", "dpo", "Advanced",
     "Directly optimizing policy on preference pairs without training a separate reward model.",
     "Direct Preference Optimization mathematically reformulates the RL objective, expressing reward in closed form as the log ratio of policy probabilities to reference probabilities: r(x, y) = beta * log(pi_theta(y|x) / pi_ref(y|x)).",
     "It eliminates reward model training, sampling loops, and PPO instability, achieving alignment with a single classification loss.",
     ["Collect preference pairs (x, y_w, y_l).", "Compute log probabilities of preferred and dispreferred completions under policy pi_theta and reference pi_ref.", "Minimize DPO loss: -log sigma(beta * (log(pi_theta(y_w)/pi_ref(y_w)) - log(pi_theta(y_l)/pi_ref(y_l))))."],
     "DPO simplifies alignment by deriving exact policy updates directly from preference pairs.",
     "Direct Preference Optimization: Your Language Model is Secretly a Reward Model", "https://arxiv.org/abs/2305.18290", 2023, "Rafailov et al."),

    (119, 10, "Constitutional AI", "constitutional-ai", "Intermediate",
     "Self-critique and revision loop using explicit constitution principles (RLAIF).",
     "Constitutional AI replaces human feedback with AI self-critique: the model generates a response, critiques it against a set of written principles (constitution), revises the text, and trains on the revised data.",
     "It enables scalable safety alignment without relying on extensive human moderation labor.",
     ["Model generates preliminary response to red-teaming prompt.", "Model critiques its response against constitutional rules (e.g. 'Is this harmful?').", "Model revises response to resolve critique.", "Fine-tune on finalized safe completions using DPO/RLAIF."],
     "Constitutional AI automates alignment by steering models via explicit natural language principles.",
     "Constitutional AI: Harmlessness from AI Feedback", "https://arxiv.org/abs/2212.08073", 2022, "Bai et al. (Anthropic)"),

    (120, 10, "Red Teaming", "red-teaming", "Intermediate",
     "Adversarial testing probing models for jailbreaks, bias, hallucination, and safety vulnerabilities.",
     "Red teaming uses adversarial human testers and automated attack algorithms to discover prompt injections, jailbreaks, and unsafe outputs prior to deployment.",
     "It identifies systemic failure modes and generates training data for safety alignment.",
     ["Construct adversarial attack prompts (roleplay, encoding tricks, prompt injection).", "Evaluate model refusal behavior and response safety.", "Add identified failure prompts to safety training datasets."],
     "Red teaming proactively identifies safety boundaries and security vulnerabilities before release.",
     "Red Teaming Language Models with Language Models", "https://arxiv.org/abs/2202.03286", 2022, "Perez et al."),

    (121, 10, "Guardrails & Safety Filters", "guardrails-safety-filters", "Beginner",
     "Input and output classifier layers blocking prompt injection and harmful text.",
     "Guardrail systems deploy fast classifier models (like Llama Guard) at the application boundary to inspect incoming user prompts and outgoing model completions for policy violations.",
     "They provide deterministic filtering and latency-efficient security enforcement.",
     ["Pass user prompt through input guardrail classifier.", "If prompt is flagged unsafe, return standard refusal immediately.", "If safe, pass to LLM, then check completion with output guardrail before returning to user."],
     "Guardrails provide external defense layers intercepting malicious inputs and policy violations.",
     "Llama Guard: LLM-based Input-Output Safeguard for Human-AI Conversations", "https://arxiv.org/abs/2312.06674", 2023, "Inan et al."),

    (122, 10, "Hallucination", "hallucination", "Beginner",
     "Generation of confident, plausible-sounding, but factually false assertions.",
     "Hallucination occurs when an autoregressive model predicts statistically fluent token sequences that lack factual grounding in training data or supplied context.",
     "Mitigating hallucination is essential for high-stakes domains like medicine, law, and engineering.",
     ["Model receives factual query with missing or ambiguous details.", "Autoregressive generation optimizes fluency over truth, producing fabricated facts.", "Evaluate factual consistency against verified reference knowledge bases."],
     "Hallucinations stem from the statistical nature of next-token prediction without explicit truth grounding.",
     "A Survey on Hallucination in Large Language Models", "https://arxiv.org/abs/2309.01219", 2023, "Huang et al."),

    (123, 10, "Grounding & Citations", "grounding-citations", "Intermediate",
     "Connecting generated claims to source text spans with verifiable attribution links.",
     "Grounding constraints force the model to cite specific document chunks from retrieved context for every factual assertion made in the generated completion.",
     "It allows users to audit claims against original source text.",
     ["Retrieve reference documents.", "Prompt model to generate statements paired with [1], [2] citation markers.", "Verify attribution overlap between generated claims and referenced source spans."],
     "Grounding connects model claims directly to verifiable evidence in source documents.",
     "Enabling Large Language Models to Generate Text with Citations", "https://arxiv.org/abs/2305.14627", 2023, "Gao et al."),

    (124, 10, "Alignment Tax", "alignment-tax", "Advanced",
     "Potential degradation in raw benchmark capabilities or creative output resulting from safety tuning.",
     "The alignment tax describes empirical drops in raw performance on coding, mathematical reasoning, or creative tasks following heavy RLHF safety optimization.",
     "Balancing safety constraints against general model intelligence is a key objective of alignment research.",
     ["Measure base model performance on diverse benchmarks.", "Apply aggressive RLHF safety tuning.", "Observe score drops on specific STEM benchmarks due to over-refusal or conservative policy collapse."],
     "Alignment tax highlights the engineering balance between safety guardrails and core capabilities.",
     "Training language models to follow instructions with human feedback", "https://arxiv.org/abs/2203.02155", 2022, "Ouyang et al. (InstructGPT)"),

    (125, 10, "Instruction Following", "instruction-following", "Beginner",
     "Evaluating adherence to formatting rules, constraints, and negative instructions.",
     "Instruction following measures how reliably a model complies with complex prompts (e.g. 'Write 3 paragraphs, do not use the letter e, format as bullet points').",
     "It distinguishes capable conversational assistants from basic autocomplete predictors.",
     ["Formulate prompt with specific constraints (length, forbidden words, output format).", "Evaluate output automatically against all constraint rules.", "Calculate instruction adherence score percentage."],
     "Strict instruction following ensures model outputs adhere to complex operational constraints.",
     "Instruction-Following Evaluation for Large Language Models (IFEval)", "https://arxiv.org/abs/2311.07911", 2023, "Zhou et al."),

    # 11. Efficiency & Optimization (126-139)
    (126, 11, "Quantization Overview", "quantization-overview", "Beginner",
     "Converting 32-bit floating point weights to INT8 or INT4 integers to reduce memory and compute.",
     "Quantization maps continuous high-precision floating point parameters (FP32/FP16) to low-bit integer representations (INT8/INT4) using scale factors and zero-point offsets: q = round(x / scale) + zero_point.",
     "It shrinks model VRAM footprint by 2x to 4x, enabling massive models to run on consumer hardware.",
     ["Calculate min and max range of weight tensor.", "Determine quantization scale factor s = (max - min) / (2^b - 1).", "Round floating point values to nearest integer values in range.", "Dequantize dynamically during matrix multiplication."],
     "Quantization dramatically cuts memory bandwidth requirements with minimal loss in model accuracy.",
     "A Survey of Quantization Methods for Efficient Neural Network Inference", "https://arxiv.org/abs/2103.13630", 2021, "Gholami et al."),

    (127, 11, "Post-Training Quantization (PTQ)", "post-training-quantization", "Intermediate",
     "Quantizing pre-trained model weights directly using a small calibration dataset without retraining.",
     "Post-Training Quantization calculates per-tensor or per-channel scaling factors using a small sample of calibration data to minimize quantization distortion without full model retraining.",
     "It enables fast model compression in minutes on a single machine.",
     ["Pass calibration dataset through model to collect activation distributions.", "Determine optimal clipping thresholds and scaling factors.", "Quantize weight matrices directly and save compressed checkpoint."],
     "PTQ provides rapid model compression without requiring expensive multi-GPU retraining.",
     "SmoothQuant: Accurate and Efficient Post-Training Quantization for Large Language Models", "https://arxiv.org/abs/2211.10438", 2022, "Xiao et al."),

    (128, 11, "GPTQ & AWQ", "gptq-awq", "Advanced",
     "Second-order error compensation (GPTQ) and activation-aware weight protection (AWQ) for 4-bit weights.",
     "GPTQ uses second-order Hessian matrix information to update unquantized weights and compensate for rounding errors; AWQ protects the top 1% salient weight channels based on activation magnitudes.",
     "They allow 4-bit weight compression with near-zero loss in perplexity.",
     ["GPTQ: Compute inverse Hessian matrix of layer inputs.", "AWQ: Identify 1% most salient weight channels by multiplying with average activation magnitude.", "Apply per-group quantization scaling factors across groups of 128 weights."],
     "Second-order and activation-aware techniques enable lossless 4-bit model quantization.",
     "GPTQ: Accurate Post-Training Quantization for Generative Pre-trained Transformers", "https://arxiv.org/abs/2210.17323", 2022, "Frantar et al."),

    (129, 11, "Knowledge Distillation", "knowledge-distillation", "Intermediate",
     "Training a compact student model to match the soft probability distribution of a large teacher.",
     "Knowledge distillation trains a small student network using a combination of ground truth labels and KL divergence loss against the soft probability outputs of a large teacher model: L = alpha * L_CE + (1 - alpha) * T^2 * KL(p_teacher || p_student).",
     "It transfers reasoning capabilities and nuanced probability distributions into fast lightweight models.",
     ["Pass training data through large teacher model to generate softened logits at temperature T.", "Pass same data through compact student model.", "Compute KL divergence between teacher and student distributions alongside standard task loss.", "Backpropagate and update student weights."],
     "Knowledge distillation compresses capability from massive models into fast, lightweight student networks.",
     "Distilling the Knowledge in a Neural Network", "https://arxiv.org/abs/1503.02531", 2015, "Hinton, Vinyals, Dean"),

    (130, 11, "Pruning", "pruning", "Intermediate",
     "Removing zero or low-magnitude weights: structured vs unstructured sparsity.",
     "Pruning sets low-magnitude weight connections to zero (unstructured) or removes entire rows, columns, or attention heads (structured) to reduce parameter counts.",
     "Structured pruning speeds up execution on standard hardware without requiring specialized sparse kernels.",
     ["Evaluate weight importance using magnitude or gradient sensitivity.", "Mask out lowest-scoring percentage of weights.", "Fine-tune remaining non-zero parameters to recover lost accuracy."],
     "Pruning eliminates redundant parameters to compress models and reduce inference latency.",
     "The Lottery Ticket Hypothesis: Finding Sparse, Trainable Neural Networks", "https://arxiv.org/abs/1803.03635", 2018, "Frankle, Carbin"),

    (131, 11, "LoRA (Low-Rank Adaptation)", "lora", "Intermediate",
     "Decomposing weight updates into low-rank matrices: W_new = W_0 + (B * A) * (alpha / r).",
     "LoRA freezes pre-trained weight matrix W_0 (d x k) and injects trainable rank decomposition matrices A (r x k) and B (d x r) where rank r << min(d, k).",
     "It slashes trainable parameter counts by 99% and eliminates optimizer VRAM overhead during fine-tuning.",
     ["Freeze base model weight matrix W_0.", "Initialize matrix A with Gaussian distribution and B with zeros.", "Compute forward pass: h = W_0 * x + (B * A * x) * (alpha / r).", "Train only matrices A and B, merging them back into W_0 for zero-latency deployment."],
     "LoRA parameterizes weight updates with low-rank factorizations, democratizing LLM fine-tuning.",
     "LoRA: Low-Rank Adaptation of Large Language Models", "https://arxiv.org/abs/2106.09685", 2021, "Hu et al."),

    (132, 11, "QLoRA", "qlora", "Advanced",
     "Combining 4-bit NormalFloat (NF4) quantized base models with 16-bit LoRA adapter layers.",
     "QLoRA quantizes the base model into a specialized 4-bit information-theoretically optimal format (NF4), dequantizes weights dynamically to BF16 during forward pass, and backpropagates gradients strictly into 16-bit LoRA adapters.",
     "It allows fine-tuning a 65-billion parameter model on a single 48GB GPU.",
     ["Quantize base weights to 4-bit NormalFloat (NF4).", "Apply Double Quantization to compress quantization constants.", "Use Paged Optimizers to manage memory spikes during backward pass.", "Train LoRA adapters in 16-bit precision."],
     "QLoRA enables high-quality fine-tuning of massive models on single consumer-grade GPUs.",
     "QLoRA: Efficient Finetuning of Quantized LLMs", "https://arxiv.org/abs/2305.14314", 2023, "Dettmers et al."),

    (133, 11, "Adapter Layers", "adapter-layers", "Intermediate",
     "Inserting small bottleneck feed-forward modules between frozen transformer layers.",
     "Adapter architectures insert compact bottleneck layers (down-projection, non-linearity, up-projection) with residual connections after attention and FFN blocks, keeping original parameters frozen.",
     "They provide modular task adaptation with minimal parameter overhead.",
     ["Freeze all pre-trained transformer layers.", "Insert adapter bottleneck: down-project d_model -> d_mid -> up-project d_mid -> d_model.", "Train only the inserted adapter parameters."],
     "Adapter layers enable parameter-efficient multi-task adaptation with modular weight swapping.",
     "Parameter-Efficient Transfer Learning for NLP", "https://arxiv.org/abs/1902.00751", 2019, "Houlsby et al."),

    (134, 11, "Prefix Tuning", "prefix-tuning", "Advanced",
     "Prepending trainable continuous virtual token vectors to transformer keys and values.",
     "Prefix Tuning prepends learnable continuous vectors (virtual prefixes) to the Key and Value matrices at every transformer layer, keeping all model parameters frozen.",
     "It steers generation behavior by learning task-specific continuous prompts.",
     ["Allocate trainable prefix parameter tensors P_K and P_V of length l_prefix for each layer.", "Prepend prefix vectors to sequence Keys and Values during attention computation.", "Update only prefix parameters during training."],
     "Prefix tuning steers frozen models by optimizing continuous key-value context prefixes.",
     "Prefix-Tuning: Optimizing Continuous Prompts for Generation", "https://arxiv.org/abs/2101.00190", 2021, "Li, Liang"),

    (135, 11, "PEFT Comparison", "peft-comparison", "Intermediate",
     "Side-by-side analysis of Full Fine-Tuning, LoRA, QLoRA, Adapters, and Prefix Tuning.",
     "Comparing Parameter-Efficient Fine-Tuning (PEFT) methods evaluates tradeoffs across trainable parameter count, GPU memory usage, training throughput, and downstream accuracy.",
     "Understanding these tradeoffs guides optimal fine-tuning strategy selection.",
     ["Compare memory footprint: Full (100%), LoRA (25%), QLoRA (10%).", "Compare latency and deployability: LoRA merges zero-overhead; Adapters add layer latency.", "Assess convergence speed across task types."],
     "LoRA and QLoRA offer the strongest balance of memory savings, accuracy, and zero deployment overhead.",
     "Scaling Down to Scale Up: A Guide to Parameter-Efficient Fine-Tuning", "https://arxiv.org/abs/2303.15647", 2023, "Lialin et al."),

    (136, 11, "Model Merging (SLERP, TIES, DARE)", "model-merging", "Advanced",
     "Merging weights from multiple fine-tuned models without additional training.",
     "Model merging techniques combine parameter weights from different fine-tuned checkpoints of the same base model using spherical linear interpolation (SLERP), sign resolution (TIES), or random dropout (DARE).",
     "It combines disparate skills (e.g. coding + roleplay + math) into a single unified checkpoint for zero compute cost.",
     ["Extract parameter delta vectors from base model: Delta_A = W_A - W_base and Delta_B = W_B - W_base.", "Apply TIES: trim low-magnitude values, elect majority sign, and average matching values.", "Add merged delta back to base weights."],
     "Model merging creates versatile multi-task models by fusing specialized weight vectors.",
     "TIES-Merging: Resolving Interference When Merging Models", "https://arxiv.org/abs/2306.01708", 2023, "Yadav et al."),

    (137, 11, "Mixture of Depths", "mixture-of-depths", "Advanced",
     "Dynamically routing easy tokens past middle transformer layers to save compute.",
     "Mixture of Depths uses a lightweight router at each layer to select a fixed top-k percentage of tokens (e.g. 50%) to participate in attention and MLP compute, while remaining tokens bypass the layer via residual connections.",
     "It reduces total FLOPs per forward pass by 50% while preserving model capacity.",
     ["Router network computes scalar participation score for each token in sequence.", "Select top-k tokens based on computational budget capacity.", "Compute full transformer block for top-k tokens; pass remainder through residual skip connection."],
     "Mixture of Depths dynamically allocates compute capacity to complex tokens while bypassing easy words.",
     "Mixture-of-Depths: Dynamically allocating compute in transformer-based language models", "https://arxiv.org/abs/2404.02258", 2024, "Raposo et al. (DeepMind)"),

    (138, 11, "Early Exit", "early-exit", "Advanced",
     "Halting forward pass computation early when intermediate layer prediction confidence is high.",
     "Early exit architectures attach auxiliary classification heads to intermediate layers; if prediction entropy drops below a threshold, inference terminates immediately without executing deeper layers.",
     "It slashes average inference latency by dynamically adjusting depth per query.",
     ["Compute activations through layer l.", "Evaluate intermediate confidence metric using auxiliary classifier head.", "If confidence exceeds threshold tau, output prediction and exit; otherwise continue to layer l+1."],
     "Early exit saves computation on simple tokens while utilizing full depth on difficult queries.",
     "DeeBERT: Dynamic Early Exiting for Accelerating BERT Inference", "https://arxiv.org/abs/2004.12993", 2020, "Xin et al."),

    (139, 11, "Activation Checkpointing (Detailed)", "activation-checkpointing-detailed", "Advanced",
     "Granular memory-compute tradeoff analysis of selective activation recomputation during backprop.",
     "Activation checkpointing partitions transformer layers into segments, discarding intermediate activations within segments during forward passes and recalculating them on demand during backward passes.",
     "It reduces peak activation memory by up to 5x with minimal compute overhead.",
     ["Identify memory-heavy operations like attention softmax and SwiGLU activations.", "Discard intermediate activation tensors between segment boundaries.", "Recompute segment forward pass during backward pass to provide exact gradients."],
     "Selective activation recomputation enables larger batch sizes and context lengths on existing hardware.",
     "Reducing Activation Recomputation in Large Transformer Models", "https://arxiv.org/abs/2205.05198", 2022, "Korthikanti et al. (Megatron-LM)")
]
